-- =====================================================================
-- Trein -- generic multi-category catalog sample data.
--
-- Replaces the old sample_data_300.sql (100 phone / 100 laptop / 100
-- headphone rows across three bespoke tables) with rows in ONE generic
-- `products` table covering 12 categories (96 rows total), matching the
-- schema the backend's app/catalog package expects.
--
-- `online_link` values point to the static product website (localhost:3000).
-- with real product URLs before this goes anywhere near real customers.
-- `offline_availability` values reference the example store names in
-- backend/app/data/stores.json -- edit both together.
--
-- If you already have data in the old phone/laptop/headphone tables from
-- a previous version of this project, see migrate_to_products_table.sql
-- (sql/legacy/) to port it into this schema instead of starting over.
--
-- Usage:
--   mysql -u <username> -p retail_shop < sql/seed/01_products.sql
--
-- Then run seed/02_customer_feedback.sql for review text. The backend
-- re-indexes the catalog automatically on its next start.
-- =====================================================================

CREATE TABLE IF NOT EXISTS products (
    id                    INT AUTO_INCREMENT PRIMARY KEY,
    category              VARCHAR(100) NOT NULL,
    name                  VARCHAR(255) NOT NULL,
    brand                 VARCHAR(100) NOT NULL,
    price                 INT NOT NULL,
    mrp                   INT NULL,
    units_available       INT NULL,
    rating                DECIMAL(2,1) NULL,
    online_link           VARCHAR(500) NULL,
    offline_availability  VARCHAR(255) NULL,
    description           VARCHAR(500) NULL,
    customer_feedback     TEXT NULL,
    attributes            JSON NULL,
    -- Written back by the backend's catalog sync (see add_ingestion_status.sql).
    ingestion_status          VARCHAR(20) NULL,
    ingestion_missing_fields  JSON NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_products_category (category),
    INDEX idx_products_ingestion_status (ingestion_status)
);

-- ---------------------------------------------------------------------
-- 96 products across 12 categories
-- ---------------------------------------------------------------------
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'Trein Nova 12 Lite', 'Samsung', 14999, 17999, 42, 4.2, 'http://localhost:3000/#/p/nova-12-lite', 'Available at Trein T Nagar, Koramangala', 'A reliable everyday smartphone with a big battery and a smooth 90Hz display.', '{"ram": "6GB", "storage": "128GB", "processor": "Exynos 1330", "color": "Awesome Blue", "battery": "5000mAh", "camera": "50MP dual camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'Galaxy M35 5G', 'Samsung', 21999, 24999, 30, 4.3, 'http://localhost:3000/#/p/galaxy-m35-5g', 'Available at Trein Koramangala', 'A 5G mid-ranger with a vivid AMOLED display and all-day battery life.', '{"ram": "8GB", "storage": "128GB", "processor": "Exynos 1280", "color": "Midnight Blue", "battery": "6000mAh", "camera": "50MP triple camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'Redmi Note 14', 'Xiaomi', 18999, 21999, 55, 4.1, 'http://localhost:3000/#/p/redmi-note-14', 'Available at Trein T Nagar', 'A value-for-money phone with fast charging and a sharp AMOLED screen.', '{"ram": "8GB", "storage": "256GB", "processor": "Snapdragon 6 Gen 1", "color": "Forest Green", "battery": "5500mAh", "camera": "108MP triple camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'OnePlus Nord CE 5', 'OnePlus', 24999, 27999, 25, 4.4, 'http://localhost:3000/#/p/oneplus-nord-ce-5', 'Available at Trein Banjara Hills', 'Clean software, fast charging and a genuinely fast chipset for the price.', '{"ram": "8GB", "storage": "128GB", "processor": "Snapdragon 7 Gen 3", "color": "Marble Grey", "battery": "5500mAh", "camera": "50MP dual camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'iPhone 15', 'Apple', 69999, 79900, 18, 4.7, 'http://localhost:3000/#/p/iphone-15', 'Available at Trein T Nagar, Banjara Hills', 'Apple''s mainstream flagship with the A16 Bionic and a 48MP main camera.', '{"ram": "6GB", "storage": "128GB", "processor": "A16 Bionic", "color": "Midnight", "battery": "3349mAh", "camera": "48MP dual camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'Pixel 9', 'Google', 74999, 79999, 12, 4.6, 'http://localhost:3000/#/p/pixel-9', 'Available at Trein Koramangala', 'The best computational camera in its class, with clean stock Android.', '{"ram": "12GB", "storage": "128GB", "processor": "Google Tensor G4", "color": "Obsidian", "battery": "4700mAh", "camera": "50MP dual camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'Realme Narzo 70x', 'Realme', 12999, 14999, 60, 3.9, 'http://localhost:3000/#/p/realme-narzo-70x', 'Available at Trein T Nagar', 'A budget 5G phone built for everyday gaming and streaming.', '{"ram": "6GB", "storage": "128GB", "processor": "Dimensity 6100+", "color": "Ice Blue", "battery": "5000mAh", "camera": "50MP dual camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mobile', 'iPhone 15 Pro Max', 'Apple', 159900, 169900, 8, 4.8, 'http://localhost:3000/#/p/iphone-15-pro-max', 'Available at Trein Banjara Hills', 'Titanium build, A17 Pro chip and a 5x telephoto camera for enthusiasts.', '{"ram": "8GB", "storage": "256GB", "processor": "A17 Pro", "color": "Natural Titanium", "battery": "4441mAh", "camera": "48MP triple camera"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'Lenovo LOQ 15', 'Lenovo', 72999, 84999, 15, 4.3, 'http://localhost:3000/#/p/lenovo-loq-15', 'Available at Trein T Nagar', 'An entry gaming laptop with an RTX 4050 that also breezes through dev work.', '{"ram": "16GB", "storage": "512GB SSD", "processor": "Intel Core i5-13450HX + RTX 4050", "color": "Onyx Grey", "display": "15.6-inch FHD 144Hz"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'HP Pavilion 15', 'HP', 54999, 62999, 22, 4.0, 'http://localhost:3000/#/p/hp-pavilion-15', 'Available at Trein Koramangala', 'A dependable everyday laptop for browsing, office work and streaming.', '{"ram": "8GB", "storage": "256GB SSD", "processor": "Intel Core i3-1315U", "color": "Silver", "display": "15.6-inch FHD"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'Dell XPS 13', 'Dell', 129999, 144999, 9, 4.6, 'http://localhost:3000/#/p/dell-xps-13', 'Available at Trein Banjara Hills', 'A premium ultraportable with a near-borderless InfinityEdge display.', '{"ram": "16GB", "storage": "512GB SSD", "processor": "Intel Core Ultra 7", "color": "Platinum Silver", "display": "13.4-inch OLED"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'ASUS Vivobook 15', 'ASUS', 47999, 54999, 30, 3.9, 'http://localhost:3000/#/p/asus-vivobook-15', 'Available at Trein T Nagar', 'A well-rounded budget laptop for students and everyday productivity.', '{"ram": "8GB", "storage": "512GB SSD", "processor": "AMD Ryzen 5 7530U", "color": "Quiet Blue", "display": "15.6-inch FHD"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'MacBook Air M3', 'Apple', 114900, 119900, 14, 4.8, 'http://localhost:3000/#/p/macbook-air-m3', 'Available at Trein Banjara Hills, T Nagar', 'Fanless, all-day battery and outstanding performance-per-watt for creators.', '{"ram": "8GB", "storage": "256GB SSD", "processor": "Apple M3", "color": "Midnight", "display": "13.6-inch Liquid Retina"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'Acer Aspire 7', 'Acer', 61999, 69999, 20, 4.1, 'http://localhost:3000/#/p/acer-aspire-7', 'Available at Trein Koramangala', 'A capable laptop with a discrete GPU for light gaming and editing.', '{"ram": "16GB", "storage": "512GB SSD", "processor": "AMD Ryzen 5 7535HS + RTX 2050", "color": "Charcoal Black", "display": "15.6-inch FHD 144Hz"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'Lenovo ThinkPad E14', 'Lenovo', 68999, 76999, 17, 4.4, 'http://localhost:3000/#/p/lenovo-thinkpad-e14', 'Available at Trein T Nagar', 'A business-grade laptop built for durability and a great keyboard.', '{"ram": "16GB", "storage": "512GB SSD", "processor": "Intel Core i5-1335U", "color": "Black", "display": "14-inch FHD"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Laptop', 'HP Omen 16', 'HP', 134999, 149999, 6, 4.5, 'http://localhost:3000/#/p/hp-omen-16', 'Available at Trein Banjara Hills', 'A serious gaming laptop with a high-refresh QHD panel and RTX 4060.', '{"ram": "16GB", "storage": "1TB SSD", "processor": "Intel Core i7-13700HX + RTX 4060", "color": "Shadow Black", "display": "16.1-inch QHD 165Hz"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'Trein Beat Buds Pro', 'boAt', 1999, 3499, 80, 4.0, 'http://localhost:3000/#/p/beat-buds-pro', 'Available at Trein T Nagar, Koramangala', 'True wireless earbuds with punchy bass and a compact charging case.', '{"type": "in-ear", "quality": "Hi-Fi", "color": "Bold Black", "battery_life": "32 hours with case", "noise_cancellation": "ENC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'Noise Buds Aero', 'Noise', 1499, 2999, 90, 3.8, 'http://localhost:3000/#/p/noise-buds-aero', 'Available at Trein T Nagar', 'Lightweight everyday earbuds with quick pairing and long battery life.', '{"type": "in-ear", "quality": "Standard", "color": "Cosmic Grey", "battery_life": "40 hours with case", "noise_cancellation": "ENC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'Sony WH-1000XM5', 'Sony', 26999, 34990, 12, 4.8, 'http://localhost:3000/#/p/sony-wh-1000xm5', 'Available at Trein Banjara Hills', 'The class-leading noise cancelling over-ear headphone for frequent flyers.', '{"type": "over-ear", "quality": "Studio", "color": "Midnight Blue", "battery_life": "30 hours", "noise_cancellation": "Adaptive ANC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'JBL Tune 760NC', 'JBL', 4999, 6999, 35, 4.2, 'http://localhost:3000/#/p/jbl-tune-760nc', 'Available at Trein Koramangala', 'Comfortable, foldable over-ear headphones with solid active noise cancelling.', '{"type": "over-ear", "quality": "Hi-Fi", "color": "Black", "battery_life": "50 hours", "noise_cancellation": "Active ANC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'Apple AirPods Pro 2', 'Apple', 24900, 26900, 20, 4.7, 'http://localhost:3000/#/p/airpods-pro-2', 'Available at Trein T Nagar, Banjara Hills', 'Excellent noise cancellation with seamless integration across Apple devices.', '{"type": "in-ear", "quality": "Studio", "color": "White", "battery_life": "30 hours with case", "noise_cancellation": "Active ANC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'boAt Rockerz 550', 'boAt', 1799, 3490, 60, 3.9, 'http://localhost:3000/#/p/boat-rockerz-550', 'Available at Trein T Nagar', 'A budget over-ear headphone with big bass for long listening sessions.', '{"type": "over-ear", "quality": "Standard", "color": "Carbon Black", "battery_life": "20 hours", "noise_cancellation": "None"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'Sennheiser Momentum 4', 'Sennheiser', 22999, 29990, 10, 4.6, 'http://localhost:3000/#/p/sennheiser-momentum-4', 'Available at Trein Banjara Hills', 'Audiophile-grade sound with up to 60 hours of battery life.', '{"type": "over-ear", "quality": "Studio", "color": "Graphite", "battery_life": "60 hours", "noise_cancellation": "Adaptive ANC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Headphone', 'OnePlus Buds 3', 'OnePlus', 5999, 6999, 45, 4.3, 'http://localhost:3000/#/p/oneplus-buds-3', 'Available at Trein Koramangala', 'Snappy, well-tuned earbuds with strong ANC for the price.', '{"type": "in-ear", "quality": "Hi-Fi", "color": "Splendid Silver", "battery_life": "44 hours with case", "noise_cancellation": "Active ANC"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'Trein Vision 43 Smart', 'Mi', 22999, 29999, 25, 4.1, 'http://localhost:3000/#/p/vision-43-smart', 'Available at Trein T Nagar, Koramangala', 'A crisp Full HD smart TV with Android TV and Dolby Audio.', '{"screen_size": "43 inch", "resolution": "Full HD", "type": "Smart LED TV", "color": "Black", "smart_features": "Android TV, Chromecast built-in"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'Samsung Crystal 4K 50', 'Samsung', 38999, 47999, 18, 4.4, 'http://localhost:3000/#/p/samsung-crystal-4k-50', 'Available at Trein Koramangala', 'Vivid 4K picture quality with Samsung''s Crystal Processor.', '{"screen_size": "50 inch", "resolution": "4K UHD", "type": "Smart LED TV", "color": "Black", "smart_features": "Tizen OS, Alexa built-in"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'LG UHD AI ThinQ 55', 'LG', 49999, 62999, 14, 4.5, 'http://localhost:3000/#/p/lg-uhd-ai-thinq-55', 'Available at Trein Banjara Hills', 'AI-upscaled 4K visuals with webOS and full smart home integration.', '{"screen_size": "55 inch", "resolution": "4K UHD", "type": "Smart LED TV", "color": "Black", "smart_features": "webOS, Google Assistant, Alexa"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'Sony Bravia X75L 55', 'Sony', 64999, 74990, 9, 4.6, 'http://localhost:3000/#/p/sony-bravia-x75l-55', 'Available at Trein T Nagar', 'Sony''s X1 processor delivers clean, natural 4K HDR picture quality.', '{"screen_size": "55 inch", "resolution": "4K UHD", "type": "Smart LED TV", "color": "Black", "smart_features": "Google TV, Chromecast built-in"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'OnePlus TV Y1S 32', 'OnePlus', 13999, 17999, 40, 4.0, 'http://localhost:3000/#/p/oneplus-tv-y1s-32', 'Available at Trein T Nagar', 'A compact, affordable smart TV great for a bedroom or study.', '{"screen_size": "32 inch", "resolution": "HD Ready", "type": "Smart LED TV", "color": "Black", "smart_features": "Android TV, Chromecast built-in"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'TCL QLED 65', 'TCL', 54999, 69999, 7, 4.3, 'http://localhost:3000/#/p/tcl-qled-65', 'Available at Trein Banjara Hills', 'A large-format QLED TV with wide colour and deep contrast for movie nights.', '{"screen_size": "65 inch", "resolution": "4K QLED", "type": "Smart LED TV", "color": "Black", "smart_features": "Google TV, hands-free voice control"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'Samsung Neo QLED 65', 'Samsung', 129999, 154999, 4, 4.7, 'http://localhost:3000/#/p/samsung-neo-qled-65', 'Available at Trein Banjara Hills', 'Mini-LED backlighting for near-OLED contrast at a lower price point.', '{"screen_size": "65 inch", "resolution": "4K Neo QLED", "type": "Smart LED TV", "color": "Black", "smart_features": "Tizen OS, Gaming Hub"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Television', 'Mi 5A 40', 'Mi', 19999, 24999, 30, 4.0, 'http://localhost:3000/#/p/mi-5a-40', 'Available at Trein Koramangala', 'A well-rounded mid-size smart TV for everyday family viewing.', '{"screen_size": "40 inch", "resolution": "Full HD", "type": "Smart LED TV", "color": "Black", "smart_features": "Android TV, PatchWall"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Trein Frost Free 260L', 'LG', 27999, 33999, 20, 4.2, 'http://localhost:3000/#/p/frost-free-260l', 'Available at Trein T Nagar, Koramangala', 'A convertible frost-free fridge with smart inverter for lower running costs.', '{"capacity": "260L", "type": "Double Door", "star_rating": "3 Star", "color": "Shiny Steel", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Samsung Digital Inverter 236L', 'Samsung', 24999, 29999, 22, 4.1, 'http://localhost:3000/#/p/samsung-digital-inverter-236l', 'Available at Trein Koramangala', 'Quiet, energy-efficient cooling with a spacious vegetable box.', '{"capacity": "236L", "type": "Double Door", "star_rating": "3 Star", "color": "Elegant Inox", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Whirlpool IceMagic 190L', 'Whirlpool', 15999, 18999, 35, 3.9, 'http://localhost:3000/#/p/whirlpool-icemagic-190l', 'Available at Trein T Nagar', 'A compact single-door fridge perfect for small families.', '{"capacity": "190L", "type": "Single Door", "star_rating": "2 Star", "color": "Wine Fiesta", "defrost": "Direct Cool"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Haier Bottom Mount 345L', 'Haier', 42999, 49999, 10, 4.4, 'http://localhost:3000/#/p/haier-bottom-mount-345l', 'Available at Trein Banjara Hills', 'A large family fridge with the freezer on the bottom for easy access.', '{"capacity": "345L", "type": "Bottom Mount", "star_rating": "3 Star", "color": "Black Steel", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'LG Side-by-Side 655L', 'LG', 89999, 104999, 5, 4.6, 'http://localhost:3000/#/p/lg-side-by-side-655l', 'Available at Trein Banjara Hills', 'A premium large-capacity fridge with a built-in water dispenser.', '{"capacity": "655L", "type": "Side by Side", "star_rating": "3 Star", "color": "Platinum Silver", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Godrej Eon 221L', 'Godrej', 19999, 23999, 28, 4.0, 'http://localhost:3000/#/p/godrej-eon-221l', 'Available at Trein T Nagar', 'A reliable double-door fridge with toughened glass shelves.', '{"capacity": "221L", "type": "Double Door", "star_rating": "3 Star", "color": "Aqua Blue", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Samsung Family Hub 580L', 'Samsung', 129999, 149999, 3, 4.7, 'http://localhost:3000/#/p/samsung-family-hub-580l', 'Available at Trein Banjara Hills', 'A smart fridge with an internal camera and touchscreen for grocery planning.', '{"capacity": "580L", "type": "Side by Side", "star_rating": "5 Star", "color": "Matte Black", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Refrigerator', 'Whirlpool 300L 3 Star', 'Whirlpool', 29999, 34999, 16, 4.2, 'http://localhost:3000/#/p/whirlpool-300l-3-star', 'Available at Trein Koramangala', 'A spacious double-door fridge with 6th Sense freshness technology.', '{"capacity": "300L", "type": "Double Door", "star_rating": "3 Star", "color": "Steel Onyx", "defrost": "Frost Free"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Trein Spin Clean 7kg', 'LG', 24999, 29999, 18, 4.1, 'http://localhost:3000/#/p/spin-clean-7kg', 'Available at Trein T Nagar', 'A fully-automatic front load washer with a smooth inverter motor.', '{"capacity": "7kg", "type": "Front Load", "star_rating": "5 Star", "color": "Middle Black", "spin_speed": "1200 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Samsung EcoBubble 7kg', 'Samsung', 26999, 32999, 15, 4.3, 'http://localhost:3000/#/p/samsung-ecobubble-7kg', 'Available at Trein Koramangala', 'Bubble technology dissolves detergent faster for better cleaning at low temps.', '{"capacity": "7kg", "type": "Front Load", "star_rating": "5 Star", "color": "Silver", "spin_speed": "1200 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Whirlpool Stainwash 6.5kg', 'Whirlpool', 13999, 16999, 30, 3.9, 'http://localhost:3000/#/p/whirlpool-stainwash-6-5kg', 'Available at Trein T Nagar', 'A dependable top-load washer with a dedicated stain removal cycle.', '{"capacity": "6.5kg", "type": "Top Load", "star_rating": "3 Star", "color": "Grey", "spin_speed": "700 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'IFB Senator 8kg', 'IFB', 34999, 41999, 9, 4.5, 'http://localhost:3000/#/p/ifb-senator-8kg', 'Available at Trein Banjara Hills', 'A premium front-load washer with an in-built heater and steam wash.', '{"capacity": "8kg", "type": "Front Load", "star_rating": "5 Star", "color": "White", "spin_speed": "1400 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Bosch Series 4 7kg', 'Bosch', 29999, 35999, 12, 4.4, 'http://localhost:3000/#/p/bosch-series-4-7kg', 'Available at Trein Banjara Hills', 'German engineering with a quiet, durable motor and an anti-vibration design.', '{"capacity": "7kg", "type": "Front Load", "star_rating": "5 Star", "color": "White", "spin_speed": "1000 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'LG Top Load 6.5kg', 'LG', 15999, 18999, 26, 4.0, 'http://localhost:3000/#/p/lg-top-load-6-5kg', 'Available at Trein T Nagar', 'Smart inverter top-load washer with a jet spray for pre-wash.', '{"capacity": "6.5kg", "type": "Top Load", "star_rating": "4 Star", "color": "Blue", "spin_speed": "740 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Haier Semi-Automatic 8kg', 'Haier', 10999, 12999, 40, 3.7, 'http://localhost:3000/#/p/haier-semi-automatic-8kg', 'Available at Trein Koramangala', 'A budget-friendly semi-automatic washer for larger loads.', '{"capacity": "8kg", "type": "Semi Automatic", "star_rating": "Not Rated", "color": "Grey", "spin_speed": "1300 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Washing Machine', 'Samsung Front Load 9kg', 'Samsung', 42999, 49999, 6, 4.6, 'http://localhost:3000/#/p/samsung-front-load-9kg', 'Available at Trein Banjara Hills', 'A large-capacity washer with AI-powered wash cycles and a quiet motor.', '{"capacity": "9kg", "type": "Front Load", "star_rating": "5 Star", "color": "Black Caviar", "spin_speed": "1400 RPM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Trein Cool Breeze 1.5 Ton', 'Voltas', 32999, 38999, 25, 4.1, 'http://localhost:3000/#/p/cool-breeze-1-5-ton', 'Available at Trein T Nagar, Koramangala', 'A reliable split AC with fast cooling for mid-sized rooms.', '{"capacity": "1.5 Ton", "type": "Split AC", "star_rating": "3 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Blue Star 1 Ton', 'Blue Star', 27999, 32999, 30, 4.0, 'http://localhost:3000/#/p/blue-star-1-ton', 'Available at Trein T Nagar', 'A compact inverter AC ideal for a small bedroom or study.', '{"capacity": "1 Ton", "type": "Split AC", "star_rating": "3 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'LG Dual Inverter 1.5 Ton', 'LG', 36999, 43999, 18, 4.4, 'http://localhost:3000/#/p/lg-dual-inverter-1-5-ton', 'Available at Trein Koramangala', 'Dual Inverter compressor for faster cooling and lower electricity bills.', '{"capacity": "1.5 Ton", "type": "Split AC", "star_rating": "5 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Daikin 2 Ton', 'Daikin', 49999, 57999, 8, 4.6, 'http://localhost:3000/#/p/daikin-2-ton', 'Available at Trein Banjara Hills', 'A powerful, whisper-quiet AC built for larger living rooms.', '{"capacity": "2 Ton", "type": "Split AC", "star_rating": "4 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Samsung Windfree 1.5 Ton', 'Samsung', 44999, 52999, 10, 4.5, 'http://localhost:3000/#/p/samsung-windfree-1-5-ton', 'Available at Trein Banjara Hills', 'WindFree cooling spreads cool air gently without a direct, chilly draft.', '{"capacity": "1.5 Ton", "type": "Split AC", "star_rating": "5 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Voltas Window AC 1.5 Ton', 'Voltas', 24999, 29999, 22, 3.9, 'http://localhost:3000/#/p/voltas-window-ac-1-5-ton', 'Available at Trein T Nagar', 'A straightforward, easy-to-install window AC for tighter budgets.', '{"capacity": "1.5 Ton", "type": "Window AC", "star_rating": "3 Star", "color": "White", "inverter": "No"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Hitachi 1.5 Ton', 'Hitachi', 38999, 45999, 14, 4.3, 'http://localhost:3000/#/p/hitachi-1-5-ton', 'Available at Trein Koramangala', 'Known for durability, with a copper condenser for long-term reliability.', '{"capacity": "1.5 Ton", "type": "Split AC", "star_rating": "4 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Air Conditioner', 'Panasonic 1 Ton', 'Panasonic', 28999, 33999, 20, 4.1, 'http://localhost:3000/#/p/panasonic-1-ton', 'Available at Trein T Nagar', 'A well-balanced inverter AC with a nanoe-G air purification filter.', '{"capacity": "1 Ton", "type": "Split AC", "star_rating": "3 Star", "color": "White", "inverter": "Yes"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Trein QuickCook 20L', 'IFB', 8999, 10999, 30, 4.0, 'http://localhost:3000/#/p/quickcook-20l', 'Available at Trein T Nagar', 'A compact solo microwave for reheating and basic cooking.', '{"capacity": "20L", "type": "Solo", "color": "Black", "power": "800W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Samsung Convection 28L', 'Samsung', 13999, 16999, 20, 4.3, 'http://localhost:3000/#/p/samsung-convection-28l', 'Available at Trein Koramangala', 'Bakes, grills and reheats -- a genuine oven replacement for small kitchens.', '{"capacity": "28L", "type": "Convection", "color": "Silver", "power": "900W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'LG Grill 20L', 'LG', 10999, 12999, 25, 4.1, 'http://localhost:3000/#/p/lg-grill-20l', 'Available at Trein T Nagar', 'Adds a grilling element on top of standard microwave heating.', '{"capacity": "20L", "type": "Grill", "color": "Black", "power": "800W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Whirlpool Convection 25L', 'Whirlpool', 12999, 15999, 18, 4.2, 'http://localhost:3000/#/p/whirlpool-convection-25l', 'Available at Trein Koramangala', '6th Sense auto-cook menus take the guesswork out of baking.', '{"capacity": "25L", "type": "Convection", "color": "Silver", "power": "900W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Bajaj Solo 17L', 'Bajaj', 5999, 6999, 40, 3.8, 'http://localhost:3000/#/p/bajaj-solo-17l', 'Available at Trein T Nagar', 'A no-frills, budget solo microwave for a hostel or small kitchen.', '{"capacity": "17L", "type": "Solo", "color": "White", "power": "700W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'IFB Convection 30L', 'IFB', 15999, 18999, 12, 4.4, 'http://localhost:3000/#/p/ifb-convection-30l', 'Available at Trein Banjara Hills', 'A large-capacity convection microwave with steam clean and starter kit.', '{"capacity": "30L", "type": "Convection", "color": "Black", "power": "900W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Panasonic Grill 23L', 'Panasonic', 9999, 11999, 22, 4.0, 'http://localhost:3000/#/p/panasonic-grill-23l', 'Available at Trein Koramangala', 'A dependable grill microwave with 6 pre-set Indian menus.', '{"capacity": "23L", "type": "Grill", "color": "Black", "power": "800W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Microwave Oven', 'Godrej Solo 19L', 'Godrej', 6999, 8499, 35, 3.9, 'http://localhost:3000/#/p/godrej-solo-19l', 'Available at Trein T Nagar', 'A compact, energy-efficient solo microwave for everyday reheating.', '{"capacity": "19L", "type": "Solo", "color": "Wine Red", "power": "700W"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Trein Pulse Fit', 'Noise', 1999, 3499, 60, 3.9, 'http://localhost:3000/#/p/pulse-fit', 'Available at Trein T Nagar', 'An affordable fitness watch with 100+ sports modes and SpO2 tracking.', '{"display": "1.85-inch AMOLED", "battery_life": "7 days", "color": "Jet Black", "water_resistance": "IP68"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'boAt Wave Neo', 'boAt', 1499, 2999, 70, 3.8, 'http://localhost:3000/#/p/boat-wave-neo', 'Available at Trein T Nagar', 'A budget smartwatch with Bluetooth calling and a bright always-on display.', '{"display": "1.83-inch TFT", "battery_life": "5 days", "color": "Active Black", "water_resistance": "IP68"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Apple Watch SE', 'Apple', 29900, 32900, 15, 4.6, 'http://localhost:3000/#/p/apple-watch-se', 'Available at Trein Banjara Hills', 'Tight integration with iPhone, crash detection and solid fitness tracking.', '{"display": "1.78-inch OLED", "battery_life": "18 hours", "color": "Midnight", "water_resistance": "WR50"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Samsung Galaxy Watch 7', 'Samsung', 28999, 32999, 12, 4.5, 'http://localhost:3000/#/p/samsung-galaxy-watch-7', 'Available at Trein Koramangala', 'Advanced sleep and heart-health tracking with a bright always-on display.', '{"display": "1.5-inch Super AMOLED", "battery_life": "40 hours", "color": "Green", "water_resistance": "5ATM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Amazfit GTS 4', 'Amazfit', 12999, 15999, 20, 4.2, 'http://localhost:3000/#/p/amazfit-gts-4', 'Available at Trein T Nagar', 'A slim, GPS-equipped fitness watch with a long-lasting battery.', '{"display": "1.75-inch AMOLED", "battery_life": "8 days", "color": "Graphite Black", "water_resistance": "5ATM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Fire-Boltt Phoenix', 'Fire-Boltt', 1799, 3999, 55, 3.7, 'http://localhost:3000/#/p/fire-boltt-phoenix', 'Available at Trein T Nagar', 'A well-rounded, low-cost smartwatch with Bluetooth calling.', '{"display": "1.39-inch TFT", "battery_life": "6 days", "color": "Black", "water_resistance": "IP67"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'Garmin Venu 3', 'Garmin', 44999, 49999, 6, 4.7, 'http://localhost:3000/#/p/garmin-venu-3', 'Available at Trein Banjara Hills', 'Premium sports tracking with a built-in speaker and wheelchair mode.', '{"display": "1.4-inch AMOLED", "battery_life": "14 days", "color": "Slate", "water_resistance": "5ATM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Smartwatch', 'OnePlus Watch 2', 'OnePlus', 24999, 27999, 10, 4.4, 'http://localhost:3000/#/p/oneplus-watch-2', 'Available at Trein Koramangala', 'A dual-engine Wear OS watch with genuinely long battery life.', '{"display": "1.43-inch AMOLED", "battery_life": "100 hours", "color": "Black Steel", "water_resistance": "5ATM"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Trein Slate 10', 'Lenovo', 13999, 16999, 25, 4.0, 'http://localhost:3000/#/p/slate-10', 'Available at Trein T Nagar', 'A budget-friendly tablet great for streaming and light browsing.', '{"ram": "4GB", "storage": "64GB", "processor": "MediaTek Helio G80", "color": "Storm Grey", "display": "10.1-inch FHD"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Samsung Galaxy Tab A9+', 'Samsung', 18999, 21999, 20, 4.2, 'http://localhost:3000/#/p/samsung-galaxy-tab-a9-plus', 'Available at Trein Koramangala', 'A quad-speaker tablet that''s genuinely good for watching movies.', '{"ram": "4GB", "storage": "64GB", "processor": "Snapdragon 695", "color": "Graphite", "display": "11-inch FHD+"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Apple iPad 10th Gen', 'Apple', 34900, 38900, 15, 4.6, 'http://localhost:3000/#/p/apple-ipad-10th-gen', 'Available at Trein Banjara Hills', 'The easiest tablet to recommend -- fast, well-supported and reliable.', '{"ram": "4GB", "storage": "64GB", "processor": "Apple A14 Bionic", "color": "Blue", "display": "10.9-inch Liquid Retina"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Xiaomi Pad 6', 'Xiaomi', 24999, 28999, 12, 4.4, 'http://localhost:3000/#/p/xiaomi-pad-6', 'Available at Trein T Nagar', 'A 144Hz display and Snapdragon 870 make this great value for media and light gaming.', '{"ram": "8GB", "storage": "128GB", "processor": "Snapdragon 870", "color": "Graphite Gray", "display": "11-inch 2.8K 144Hz"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Lenovo Tab P11', 'Lenovo', 21999, 25999, 14, 4.1, 'http://localhost:3000/#/p/lenovo-tab-p11', 'Available at Trein Koramangala', 'A productivity-leaning tablet with a keyboard folio option.', '{"ram": "6GB", "storage": "128GB", "processor": "MediaTek Helio G99", "color": "Storm Grey", "display": "11.5-inch 2K"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'iPad Air M2', 'Apple', 59900, 64900, 8, 4.7, 'http://localhost:3000/#/p/ipad-air-m2', 'Available at Trein Banjara Hills', 'M2 performance in a light, thin body -- great for creative work on the go.', '{"ram": "8GB", "storage": "128GB", "processor": "Apple M2", "color": "Space Grey", "display": "11-inch Liquid Retina"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Realme Pad 2', 'Realme', 16999, 19999, 18, 4.0, 'http://localhost:3000/#/p/realme-pad-2', 'Available at Trein T Nagar', 'A well-priced tablet with a sharp 2K display and quad speakers.', '{"ram": "6GB", "storage": "128GB", "processor": "MediaTek Helio G99", "color": "Grey", "display": "11.5-inch 2K"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Tablet', 'Samsung Galaxy Tab S9', 'Samsung', 72999, 79999, 5, 4.8, 'http://localhost:3000/#/p/samsung-galaxy-tab-s9', 'Available at Trein Banjara Hills', 'A flagship Android tablet with an S Pen included and an AMOLED display.', '{"ram": "8GB", "storage": "128GB", "processor": "Snapdragon 8 Gen 2", "color": "Graphite", "display": "11-inch Dynamic AMOLED 2X"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Trein Boom Mini', 'JBL', 2999, 4499, 50, 4.1, 'http://localhost:3000/#/p/boom-mini', 'Available at Trein T Nagar, Koramangala', 'A pocketable, waterproof Bluetooth speaker with surprisingly big sound.', '{"type": "Portable Bluetooth", "battery_life": "12 hours", "color": "Black", "connectivity": "Bluetooth 5.3"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'boAt Stone 1200', 'boAt', 2499, 3999, 55, 3.9, 'http://localhost:3000/#/p/boat-stone-1200', 'Available at Trein T Nagar', 'A rugged party speaker with punchy bass and RGB lighting.', '{"type": "Portable Bluetooth", "battery_life": "8 hours", "color": "Black", "connectivity": "Bluetooth 5.0"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Sony SRS-XB100', 'Sony', 3999, 5490, 30, 4.3, 'http://localhost:3000/#/p/sony-srs-xb100', 'Available at Trein Koramangala', 'Compact and durable with Sony''s signature punchy Extra Bass tuning.', '{"type": "Portable Bluetooth", "battery_life": "16 hours", "color": "Blue", "connectivity": "Bluetooth 5.3"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Amazon Echo Dot 5th Gen', 'Amazon', 4499, 5999, 40, 4.4, 'http://localhost:3000/#/p/amazon-echo-dot-5th-gen', 'Available at Trein T Nagar', 'A smart speaker with Alexa built in -- great as a bedside or kitchen assistant.', '{"type": "Smart Speaker", "battery_life": "Plugged in", "color": "Charcoal", "connectivity": "Wi-Fi, Bluetooth"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'JBL Charge 5', 'JBL', 15999, 18999, 12, 4.6, 'http://localhost:3000/#/p/jbl-charge-5', 'Available at Trein Banjara Hills', 'A powerful, waterproof speaker that can also charge your phone in a pinch.', '{"type": "Portable Bluetooth", "battery_life": "20 hours", "color": "Black", "connectivity": "Bluetooth 5.1"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Google Nest Mini', 'Google', 3499, 4499, 35, 4.2, 'http://localhost:3000/#/p/google-nest-mini', 'Available at Trein Koramangala', 'A compact smart speaker with Google Assistant and surprisingly good bass.', '{"type": "Smart Speaker", "battery_life": "Plugged in", "color": "Chalk", "connectivity": "Wi-Fi, Bluetooth"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Marshall Emberton II', 'Marshall', 12999, 14999, 10, 4.7, 'http://localhost:3000/#/p/marshall-emberton-ii', 'Available at Trein Banjara Hills', 'Iconic Marshall styling with genuinely excellent, room-filling sound.', '{"type": "Portable Bluetooth", "battery_life": "30 hours", "color": "Black and Brass", "connectivity": "Bluetooth 5.1"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Speaker', 'Zebronics Zeb-County', 'Zebronics', 999, 1699, 65, 3.6, 'http://localhost:3000/#/p/zebronics-zeb-county', 'Available at Trein T Nagar', 'An ultra-budget portable speaker with FM radio and an SD card slot.', '{"type": "Portable Bluetooth", "battery_life": "6 hours", "color": "Black", "connectivity": "Bluetooth 5.0"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Trein PowerMix 750', 'Bajaj', 2999, 3999, 45, 4.0, 'http://localhost:3000/#/p/powermix-750', 'Available at Trein T Nagar', 'A dependable everyday mixer grinder with three stainless steel jars.', '{"power": "750W", "jars": "3", "color": "White", "speed_settings": "3-speed + pulse"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Preethi Zodiac', 'Preethi', 5999, 7499, 25, 4.4, 'http://localhost:3000/#/p/preethi-zodiac', 'Available at Trein Koramangala', 'A powerful mixer with a dedicated wet-grinding jar for idli/dosa batter.', '{"power": "750W", "jars": "4", "color": "Blue", "speed_settings": "3-speed + pulse"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Philips HL7756', 'Philips', 4499, 5999, 30, 4.2, 'http://localhost:3000/#/p/philips-hl7756', 'Available at Trein T Nagar', 'A well-balanced mixer with a strong motor and durable blades.', '{"power": "750W", "jars": "3", "color": "Black", "speed_settings": "3-speed + pulse"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Butterfly Rapid', 'Butterfly', 3499, 4499, 38, 3.9, 'http://localhost:3000/#/p/butterfly-rapid', 'Available at Trein T Nagar', 'A compact mixer grinder that''s easy to store in a small kitchen.', '{"power": "600W", "jars": "3", "color": "Red", "speed_settings": "3-speed"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Bosch TrueMixx Pro', 'Bosch', 6999, 8999, 15, 4.5, 'http://localhost:3000/#/p/bosch-truemixx-pro', 'Available at Trein Banjara Hills', 'German motor engineering with an overload protector for heavy daily use.', '{"power": "1000W", "jars": "4", "color": "Silver", "speed_settings": "4-speed + pulse"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Prestige Iris', 'Prestige', 3999, 4999, 40, 4.1, 'http://localhost:3000/#/p/prestige-iris', 'Available at Trein Koramangala', 'A reliable, no-fuss mixer with a 5-year motor warranty.', '{"power": "750W", "jars": "3", "color": "White", "speed_settings": "3-speed"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Havells Endura', 'Havells', 5499, 6999, 20, 4.3, 'http://localhost:3000/#/p/havells-endura', 'Available at Trein T Nagar', 'A durable mixer with copper motor windings for a longer service life.', '{"power": "750W", "jars": "4", "color": "Red", "speed_settings": "3-speed + pulse"}');
INSERT INTO products (category, name, brand, price, mrp, units_available, rating, online_link, offline_availability, description, attributes) VALUES ('Mixer Grinder', 'Inalsa Robot Chef+', 'Inalsa', 4999, 6499, 22, 4.0, 'http://localhost:3000/#/p/inalsa-robot-chef-plus', 'Available at Trein Koramangala', 'A versatile mixer with an extra chutney jar and a strong 750W motor.', '{"power": "750W", "jars": "4", "color": "Grey", "speed_settings": "3-speed + pulse"}');
