-- =====================================================================
-- Agentic SalesMan -- 300 sample catalog rows (100 phone / 100 laptop /
-- 100 headphone), matching the schema BACKEND/DATABASE/SQL_CONNECTOR.py
-- and TOOLS/product_tools.py expect.
--
-- Base columns (name, brand, price, processor/type, ram/quality,
-- storage, color) are what the sales-agent RAG pipeline already reads
-- today. The extra columns (mrp, units_available, rating, online_link,
-- offline_availability) are OPTIONAL enrichments picked up automatically
-- by WORKFLOW/recommendations.py + WORKFLOW/scoring.py when present --
-- they're what unlocks the discount %, stock count, "Buy Online" link
-- and offline-availability line on the frontend's Buy Now card, plus the
-- rating component of the recommendation score (see scoring.py's
-- RATING_COLUMN_NAMES / WORKFLOW/recommendations.py's *_COLUMNS lists).
-- `online_link` values below are PLACEHOLDER URLs (your-store.example)
-- -- replace them with real product URLs before this goes anywhere near
-- real customers.
--
-- Usage:
--   1. If your `phone`/`laptop`/`headphone` tables don't exist yet, the
--      CREATE TABLE IF NOT EXISTS blocks below create them.
--   2. If they already exist (this looks like your case -- your chat
--      already returns real phone/laptop/headphone results), run just
--      the ALTER TABLE block to add the optional enrichment columns.
--      MySQL will error with "Duplicate column name" for any column you
--      already have -- that's harmless, just delete that one line and
--      re-run the rest.
--   3. Then run the INSERT statements. After they land, restart the
--      backend once (or delete WORKFLOW/chroma_db/) so the row-count
--      sync in SQL_CONNECTOR.py notices the new rows and re-embeds them
--      into Chroma -- otherwise the RAG store keeps using the old data.
--
--   mysql -u <username> -p retail_shop < sample_data_300.sql
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. Tables (safe no-op if they already exist)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS phone (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    brand               VARCHAR(100) NOT NULL,
    price               INT NOT NULL,
    mrp                 INT NULL,
    processor           VARCHAR(100) NULL,
    ram                 VARCHAR(20) NULL,
    storage             VARCHAR(20) NULL,
    color               VARCHAR(50) NULL,
    units_available     INT NULL,
    rating              DECIMAL(2,1) NULL,
    online_link         VARCHAR(500) NULL,
    offline_availability VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS laptop (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    brand               VARCHAR(100) NOT NULL,
    price               INT NOT NULL,
    mrp                 INT NULL,
    processor           VARCHAR(100) NULL,
    ram                 VARCHAR(20) NULL,
    storage             VARCHAR(20) NULL,
    color               VARCHAR(50) NULL,
    units_available     INT NULL,
    rating              DECIMAL(2,1) NULL,
    online_link         VARCHAR(500) NULL,
    offline_availability VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS headphone (
    id                  INT AUTO_INCREMENT PRIMARY KEY,
    name                VARCHAR(255) NOT NULL,
    brand               VARCHAR(100) NOT NULL,
    price               INT NOT NULL,
    mrp                 INT NULL,
    type                VARCHAR(100) NULL,
    quality             VARCHAR(100) NULL,
    color               VARCHAR(50) NULL,
    units_available     INT NULL,
    rating              DECIMAL(2,1) NULL,
    online_link         VARCHAR(500) NULL,
    offline_availability VARCHAR(255) NULL
);

-- ---------------------------------------------------------------------
-- 2. Optional enrichment columns for EXISTING tables that only have the
--    base columns today (delete any single line MySQL calls a duplicate)
-- ---------------------------------------------------------------------
ALTER TABLE phone     ADD COLUMN mrp INT NULL, ADD COLUMN units_available INT NULL, ADD COLUMN rating DECIMAL(2,1) NULL, ADD COLUMN online_link VARCHAR(500) NULL, ADD COLUMN offline_availability VARCHAR(255) NULL;
ALTER TABLE laptop    ADD COLUMN mrp INT NULL, ADD COLUMN units_available INT NULL, ADD COLUMN rating DECIMAL(2,1) NULL, ADD COLUMN online_link VARCHAR(500) NULL, ADD COLUMN offline_availability VARCHAR(255) NULL;
ALTER TABLE headphone ADD COLUMN mrp INT NULL, ADD COLUMN units_available INT NULL, ADD COLUMN rating DECIMAL(2,1) NULL, ADD COLUMN online_link VARCHAR(500) NULL, ADD COLUMN offline_availability VARCHAR(255) NULL;

-- ---------------------------------------------------------------------
-- 3. Seed data -- 100 rows per table, 300 total
-- ---------------------------------------------------------------------
-- PHONES (100)
INSERT INTO phone
    (name, brand, price, mrp, processor, ram, storage, color, units_available, rating, online_link, offline_availability)
VALUES
    ('POCO X6 - Forest Green', 'Xiaomi', 18999, 18999, 'Snapdragon 8 Gen 2', '4GB', '1TB', 'Forest Green', 45, 3.7, 'https://your-store.example/phone/poco-x6---forest-green', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Realme 11x - Storm Silver', 'Realme', 49999, 56820, 'Dimensity 7050', '16GB', '512GB', 'Storm Silver', 8, 3.8, 'https://your-store.example/phone/realme-11x---storm-silver', 'In stock at authorized brand stores in major cities'),
    ('Galaxy M14 - Pearl White', 'Samsung', 15999, 19510, 'Snapdragon 8 Gen 2 for Galaxy', '8GB', '1TB', 'Pearl White', 12, 4.5, 'https://your-store.example/phone/galaxy-m14---pearl-white', 'Available at Vijay Sales outlets nationwide'),
    ('OnePlus 11 - Titanium Gray', 'OnePlus', 18999, 21590, 'Snapdragon 7+ Gen 2', '12GB', '128GB', 'Titanium Gray', 2, 4.8, 'https://your-store.example/phone/oneplus-11---titanium-gray', 'Not available in offline stores'),
    ('Galaxy S24+ - Midnight Black', 'Samsung', 15999, 18180, 'Snapdragon 8 Gen 2 for Galaxy', '16GB', '256GB', 'Midnight Black', 12, 4.3, 'https://your-store.example/phone/galaxy-s24+---midnight-black', 'Available at flagship brand stores only'),
    ('Moto G84 - Sunset Orange', 'Motorola', 15999, 15999, 'Snapdragon 695', '8GB', '512GB', 'Sunset Orange', 0, 4.5, 'https://your-store.example/phone/moto-g84---sunset-orange', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy A54 - Sunset Orange', 'Samsung', 44999, 44999, 'Snapdragon 8 Gen 2 for Galaxy', '12GB', '256GB', 'Sunset Orange', 20, 3.9, 'https://your-store.example/phone/galaxy-a54---sunset-orange', 'Available at flagship brand stores only'),
    ('OnePlus 12 - Titanium Gray', 'OnePlus', 89999, 94740, 'Snapdragon 8 Gen 2', '6GB', '256GB', 'Titanium Gray', 5, 4.0, 'https://your-store.example/phone/oneplus-12---titanium-gray', 'Not available in offline stores'),
    ('Vivo X90 - Titanium Gray', 'Vivo', 25999, 28890, 'Dimensity 8200', '12GB', '1TB', 'Titanium Gray', 2, 4.6, 'https://your-store.example/phone/vivo-x90---titanium-gray', 'Available at flagship brand stores only'),
    ('Pixel 8 - Rose Gold', 'Google', 69999, 73680, 'Tensor G3', '12GB', '128GB', 'Rose Gold', 0, 3.7, 'https://your-store.example/phone/pixel-8---rose-gold', 'In stock at authorized brand stores in major cities'),
    ('Nothing Phone (2a) - Pearl White', 'Nothing', 9999, 11110, 'Snapdragon 8+ Gen 1', '16GB', '128GB', 'Pearl White', 8, 3.4, 'https://your-store.example/phone/nothing-phone-2a---pearl-white', 'Not available in offline stores'),
    ('Vivo V29 - Forest Green', 'Vivo', 159999, 200000, 'Snapdragon 8 Gen 2', '8GB', '128GB', 'Forest Green', 45, 4.4, 'https://your-store.example/phone/vivo-v29---forest-green', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Pixel 8 Pro - Midnight Black', 'Google', 79999, 94120, 'Tensor G3', '12GB', '512GB', 'Midnight Black', 0, 4.1, 'https://your-store.example/phone/pixel-8-pro---midnight-black', 'Not available in offline stores'),
    ('Galaxy S23 Ultra - Midnight Black', 'Samsung', 29999, 31580, 'Exynos 2200', '6GB', '512GB', 'Midnight Black', 0, 3.9, 'https://your-store.example/phone/galaxy-s23-ultra---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('iPhone 13 - Titanium Gray', 'Apple', 9999, 9999, 'Apple A17 Pro', '6GB', '1TB', 'Titanium Gray', 12, 4.3, 'https://your-store.example/phone/iphone-13---titanium-gray', 'Available at select Croma and Reliance Digital stores'),
    ('Realme GT 5 - Pearl White', 'Realme', 159999, 181820, 'Dimensity 7050', '6GB', '256GB', 'Pearl White', 45, 3.9, 'https://your-store.example/phone/realme-gt-5---pearl-white', 'Available at select Croma and Reliance Digital stores'),
    ('OnePlus 12R - Titanium Gray', 'OnePlus', 89999, 100000, 'Snapdragon 8 Gen 3', '12GB', '512GB', 'Titanium Gray', 0, 3.6, 'https://your-store.example/phone/oneplus-12r---titanium-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Galaxy A34 - Forest Green', 'Samsung', 39999, 39999, 'Exynos 1380', '6GB', '1TB', 'Forest Green', 5, 4.8, 'https://your-store.example/phone/galaxy-a34---forest-green', 'Available at flagship brand stores only'),
    ('Redmi Note 13 Pro - Forest Green', 'Xiaomi', 21999, 27500, 'Snapdragon 8 Gen 2', '16GB', '64GB', 'Forest Green', 8, 4.9, 'https://your-store.example/phone/redmi-note-13-pro---forest-green', 'Available at select Croma and Reliance Digital stores'),
    ('Realme 12 Pro - Rose Gold', 'Realme', 99999, 108690, 'Dimensity 7050', '6GB', '256GB', 'Rose Gold', 30, 4.2, 'https://your-store.example/phone/realme-12-pro---rose-gold', 'Available at flagship brand stores only'),
    ('Moto Edge 40 - Forest Green', 'Motorola', 34999, 41180, 'Snapdragon 8s Gen 3', '6GB', '128GB', 'Forest Green', 5, 3.7, 'https://your-store.example/phone/moto-edge-40---forest-green', 'Not available in offline stores'),
    ('Xiaomi 13 Pro - Forest Green', 'Xiaomi', 9999, 11110, 'Snapdragon 7 Gen 1', '8GB', '512GB', 'Forest Green', 5, 4.4, 'https://your-store.example/phone/xiaomi-13-pro---forest-green', 'Available at Vijay Sales outlets nationwide'),
    ('Moto Razr 40 Ultra - Sunset Orange', 'Motorola', 54999, 54999, 'Dimensity 8020', '4GB', '128GB', 'Sunset Orange', 5, 4.1, 'https://your-store.example/phone/moto-razr-40-ultra---sunset-orange', 'Available at Vijay Sales outlets nationwide'),
    ('Pixel 8a - Pearl White', 'Google', 89999, 89999, 'Tensor G2', '12GB', '256GB', 'Pearl White', 0, 4.8, 'https://your-store.example/phone/pixel-8a---pearl-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Oppo A78 - Pearl White', 'Oppo', 89999, 89999, 'Dimensity 7050', '12GB', '256GB', 'Pearl White', 15, 4.1, 'https://your-store.example/phone/oppo-a78---pearl-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('OnePlus Nord CE 3 - Titanium Gray', 'OnePlus', 25999, 27370, 'Snapdragon 8 Gen 2', '6GB', '64GB', 'Titanium Gray', 45, 4.8, 'https://your-store.example/phone/oneplus-nord-ce-3---titanium-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('iPhone 14 - Ocean Blue', 'Apple', 159999, 168420, 'Apple A17 Pro', '12GB', '256GB', 'Ocean Blue', 30, 4.2, 'https://your-store.example/phone/iphone-14---ocean-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Oppo Reno 11 - Midnight Black', 'Oppo', 18999, 20650, 'Dimensity 8200', '6GB', '512GB', 'Midnight Black', 5, 3.4, 'https://your-store.example/phone/oppo-reno-11---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('OnePlus Nord 3 - Rose Gold', 'OnePlus', 99999, 111110, 'Snapdragon 8 Gen 2', '16GB', '256GB', 'Rose Gold', 30, 4.0, 'https://your-store.example/phone/oneplus-nord-3---rose-gold', 'In stock at authorized brand stores in major cities'),
    ('Oppo Reno 10 - Midnight Black', 'Oppo', 54999, 64700, 'Snapdragon 695', '16GB', '1TB', 'Midnight Black', 30, 3.6, 'https://your-store.example/phone/oppo-reno-10---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('Galaxy S23 - Midnight Black', 'Samsung', 79999, 84210, 'Exynos 2200', '16GB', '64GB', 'Midnight Black', 2, 3.6, 'https://your-store.example/phone/galaxy-s23---midnight-black', 'Available at flagship brand stores only'),
    ('Nothing Phone (1) - Titanium Gray', 'Nothing', 119999, 150000, 'Snapdragon 778G+', '8GB', '1TB', 'Titanium Gray', 30, 4.1, 'https://your-store.example/phone/nothing-phone-1---titanium-gray', 'Available at select Croma and Reliance Digital stores'),
    ('Pixel 7 - Midnight Black', 'Google', 34999, 34999, 'Tensor G2', '8GB', '64GB', 'Midnight Black', 30, 4.1, 'https://your-store.example/phone/pixel-7---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('Pixel 7 Pro - Titanium Gray', 'Google', 79999, 106670, 'Tensor G3', '16GB', '1TB', 'Titanium Gray', 30, 3.7, 'https://your-store.example/phone/pixel-7-pro---titanium-gray', 'Available at Vijay Sales outlets nationwide'),
    ('iPhone 15 Pro Max - Sunset Orange', 'Apple', 99999, 108690, 'Apple A17 Pro', '12GB', '1TB', 'Sunset Orange', 30, 4.7, 'https://your-store.example/phone/iphone-15-pro-max---sunset-orange', 'Available at Vijay Sales outlets nationwide'),
    ('iPhone 14 Plus - Pearl White', 'Apple', 79999, 94120, 'Apple A15 Bionic', '12GB', '64GB', 'Pearl White', 20, 3.9, 'https://your-store.example/phone/iphone-14-plus---pearl-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Galaxy Z Flip 5 - Pearl White', 'Samsung', 69999, 69999, 'Exynos 2200', '6GB', '256GB', 'Pearl White', 2, 4.8, 'https://your-store.example/phone/galaxy-z-flip-5---pearl-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Vivo V30 - Forest Green', 'Vivo', 21999, 23910, 'Dimensity 8200', '6GB', '512GB', 'Forest Green', 0, 4.0, 'https://your-store.example/phone/vivo-v30---forest-green', 'Not available in offline stores'),
    ('Nothing Phone (2) - Ocean Blue', 'Nothing', 34999, 41180, 'Snapdragon 778G+', '12GB', '1TB', 'Ocean Blue', 12, 4.0, 'https://your-store.example/phone/nothing-phone-2---ocean-blue', 'Available at Vijay Sales outlets nationwide'),
    ('Oppo F23 - Forest Green', 'Oppo', 15999, 18180, 'Dimensity 8200', '8GB', '64GB', 'Forest Green', 30, 4.1, 'https://your-store.example/phone/oppo-f23---forest-green', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Xiaomi 14 - Midnight Black', 'Xiaomi', 59999, 66670, 'Dimensity 7200', '16GB', '1TB', 'Midnight Black', 30, 4.8, 'https://your-store.example/phone/xiaomi-14---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('iPhone SE (2024) - Pearl White', 'Apple', 18999, 18999, 'Apple A15 Bionic', '8GB', '256GB', 'Pearl White', 2, 3.8, 'https://your-store.example/phone/iphone-se-2024---pearl-white', 'In stock at authorized brand stores in major cities'),
    ('Vivo Y200 - Storm Silver', 'Vivo', 39999, 50000, 'Dimensity 8200', '6GB', '1TB', 'Storm Silver', 45, 4.1, 'https://your-store.example/phone/vivo-y200---storm-silver', 'Available at Vijay Sales outlets nationwide'),
    ('iPhone 15 Pro - Titanium Gray', 'Apple', 39999, 39999, 'Apple A15 Bionic', '6GB', '512GB', 'Titanium Gray', 8, 4.8, 'https://your-store.example/phone/iphone-15-pro---titanium-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('iPhone 15 - Titanium Gray', 'Apple', 39999, 39999, 'Apple A15 Bionic', '16GB', '128GB', 'Titanium Gray', 8, 4.7, 'https://your-store.example/phone/iphone-15---titanium-gray', 'Not available in offline stores'),
    ('Realme Narzo 60 - Midnight Black', 'Realme', 49999, 66670, 'Snapdragon 8s Gen 3', '12GB', '256GB', 'Midnight Black', 2, 3.5, 'https://your-store.example/phone/realme-narzo-60---midnight-black', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('POCO F5 - Pearl White', 'Xiaomi', 18999, 20000, 'Snapdragon 7 Gen 1', '8GB', '64GB', 'Pearl White', 5, 4.8, 'https://your-store.example/phone/poco-f5---pearl-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Galaxy S24 - Rose Gold', 'Samsung', 99999, 125000, 'Exynos 2200', '8GB', '512GB', 'Rose Gold', 2, 3.8, 'https://your-store.example/phone/galaxy-s24---rose-gold', 'Available at select Croma and Reliance Digital stores'),
    ('Redmi Note 13 - Rose Gold', 'Xiaomi', 12999, 16250, 'Snapdragon 7 Gen 1', '4GB', '1TB', 'Rose Gold', 5, 4.2, 'https://your-store.example/phone/redmi-note-13---rose-gold', 'In stock at authorized brand stores in major cities'),
    ('POCO X6 - Sunset Orange', 'Xiaomi', 18999, 23750, 'Snapdragon 8 Gen 2', '12GB', '512GB', 'Sunset Orange', 15, 4.9, 'https://your-store.example/phone/poco-x6---sunset-orange', 'Available at Vijay Sales outlets nationwide'),
    ('Realme 11x - Pearl White', 'Realme', 34999, 41180, 'Dimensity 7050', '6GB', '128GB', 'Pearl White', 12, 4.9, 'https://your-store.example/phone/realme-11x---pearl-white', 'In stock at authorized brand stores in major cities'),
    ('Galaxy M14 - Midnight Black', 'Samsung', 15999, 16840, 'Snapdragon 8 Gen 2 for Galaxy', '8GB', '512GB', 'Midnight Black', 0, 3.5, 'https://your-store.example/phone/galaxy-m14---midnight-black', 'Not available in offline stores'),
    ('OnePlus 11 - Rose Gold', 'OnePlus', 159999, 195120, 'Snapdragon 8 Gen 2', '8GB', '64GB', 'Rose Gold', 2, 3.6, 'https://your-store.example/phone/oneplus-11---rose-gold', 'Not available in offline stores'),
    ('Galaxy S24+ - Midnight Black (8GB)', 'Samsung', 39999, 45450, 'Exynos 1380', '8GB', '1TB', 'Midnight Black', 5, 3.5, 'https://your-store.example/phone/galaxy-s24+---midnight-black-8gb', 'Available at Vijay Sales outlets nationwide'),
    ('Moto G84 - Pearl White', 'Motorola', 54999, 64700, 'Snapdragon 695', '4GB', '256GB', 'Pearl White', 0, 4.1, 'https://your-store.example/phone/moto-g84---pearl-white', 'Available at flagship brand stores only'),
    ('Galaxy A54 - Pearl White', 'Samsung', 34999, 38890, 'Snapdragon 8 Gen 2 for Galaxy', '4GB', '64GB', 'Pearl White', 0, 3.6, 'https://your-store.example/phone/galaxy-a54---pearl-white', 'Available at flagship brand stores only'),
    ('OnePlus 12 - Midnight Black', 'OnePlus', 59999, 65220, 'Snapdragon 8 Gen 2', '8GB', '256GB', 'Midnight Black', 0, 4.3, 'https://your-store.example/phone/oneplus-12---midnight-black', 'Available at flagship brand stores only'),
    ('Vivo X90 - Ocean Blue', 'Vivo', 159999, 168420, 'Dimensity 8200', '8GB', '512GB', 'Ocean Blue', 8, 4.5, 'https://your-store.example/phone/vivo-x90---ocean-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Pixel 8 - Ocean Blue', 'Google', 12999, 16250, 'Tensor G3', '16GB', '128GB', 'Ocean Blue', 30, 4.3, 'https://your-store.example/phone/pixel-8---ocean-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Nothing Phone (2a) - Pearl White (4GB)', 'Nothing', 15999, 18180, 'Snapdragon 778G+', '4GB', '128GB', 'Pearl White', 0, 4.0, 'https://your-store.example/phone/nothing-phone-2a---pearl-white-4gb', 'Not available in offline stores'),
    ('Vivo V29 - Midnight Black', 'Vivo', 9999, 12190, 'Snapdragon 8 Gen 2', '16GB', '128GB', 'Midnight Black', 8, 3.4, 'https://your-store.example/phone/vivo-v29---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('Pixel 8 Pro - Titanium Gray', 'Google', 99999, 99999, 'Tensor G2', '12GB', '256GB', 'Titanium Gray', 8, 3.8, 'https://your-store.example/phone/pixel-8-pro---titanium-gray', 'In stock at authorized brand stores in major cities'),
    ('Galaxy S23 Ultra - Pearl White', 'Samsung', 79999, 97560, 'Exynos 1380', '12GB', '64GB', 'Pearl White', 8, 4.6, 'https://your-store.example/phone/galaxy-s23-ultra---pearl-white', 'Available at flagship brand stores only'),
    ('iPhone 13 - Pearl White', 'Apple', 15999, 17780, 'Apple A17 Pro', '6GB', '256GB', 'Pearl White', 8, 4.3, 'https://your-store.example/phone/iphone-13---pearl-white', 'In stock at authorized brand stores in major cities'),
    ('Realme GT 5 - Midnight Black', 'Realme', 89999, 89999, 'Snapdragon 7+ Gen 2', '12GB', '256GB', 'Midnight Black', 5, 4.4, 'https://your-store.example/phone/realme-gt-5---midnight-black', 'Available at Vijay Sales outlets nationwide'),
    ('OnePlus 12R - Rose Gold', 'OnePlus', 79999, 100000, 'Snapdragon 8 Gen 3', '12GB', '64GB', 'Rose Gold', 5, 3.9, 'https://your-store.example/phone/oneplus-12r---rose-gold', 'Available at select Croma and Reliance Digital stores'),
    ('Galaxy A34 - Sunset Orange', 'Samsung', 9999, 12500, 'Exynos 1380', '12GB', '64GB', 'Sunset Orange', 20, 4.9, 'https://your-store.example/phone/galaxy-a34---sunset-orange', 'Not available in offline stores'),
    ('Redmi Note 13 Pro - Pearl White', 'Xiaomi', 29999, 31580, 'Snapdragon 7 Gen 1', '16GB', '64GB', 'Pearl White', 30, 3.8, 'https://your-store.example/phone/redmi-note-13-pro---pearl-white', 'Available at Vijay Sales outlets nationwide'),
    ('Realme 12 Pro - Ocean Blue', 'Realme', 159999, 159999, 'Snapdragon 8s Gen 3', '16GB', '256GB', 'Ocean Blue', 12, 3.7, 'https://your-store.example/phone/realme-12-pro---ocean-blue', 'Not available in offline stores'),
    ('Moto Edge 40 - Storm Silver', 'Motorola', 9999, 12190, 'Snapdragon 695', '4GB', '512GB', 'Storm Silver', 15, 3.9, 'https://your-store.example/phone/moto-edge-40---storm-silver', 'In stock at authorized brand stores in major cities'),
    ('Xiaomi 13 Pro - Storm Silver', 'Xiaomi', 54999, 62500, 'Dimensity 7200', '8GB', '64GB', 'Storm Silver', 0, 3.9, 'https://your-store.example/phone/xiaomi-13-pro---storm-silver', 'Available at Vijay Sales outlets nationwide'),
    ('Moto Razr 40 Ultra - Storm Silver', 'Motorola', 18999, 21110, 'Snapdragon 695', '4GB', '256GB', 'Storm Silver', 12, 3.5, 'https://your-store.example/phone/moto-razr-40-ultra---storm-silver', 'Not available in offline stores'),
    ('Pixel 8a - Titanium Gray', 'Google', 54999, 61110, 'Tensor G3', '8GB', '64GB', 'Titanium Gray', 0, 3.5, 'https://your-store.example/phone/pixel-8a---titanium-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Oppo A78 - Rose Gold', 'Oppo', 21999, 27500, 'Dimensity 7050', '8GB', '512GB', 'Rose Gold', 12, 3.7, 'https://your-store.example/phone/oppo-a78---rose-gold', 'Available at Vijay Sales outlets nationwide'),
    ('OnePlus Nord CE 3 - Storm Silver', 'OnePlus', 9999, 12500, 'Snapdragon 7+ Gen 2', '12GB', '1TB', 'Storm Silver', 5, 4.5, 'https://your-store.example/phone/oneplus-nord-ce-3---storm-silver', 'Available at select Croma and Reliance Digital stores'),
    ('iPhone 14 - Storm Silver', 'Apple', 79999, 97560, 'Apple A17 Pro', '6GB', '256GB', 'Storm Silver', 0, 4.8, 'https://your-store.example/phone/iphone-14---storm-silver', 'Available at flagship brand stores only'),
    ('Oppo Reno 11 - Ocean Blue', 'Oppo', 25999, 28890, 'Snapdragon 695', '12GB', '256GB', 'Ocean Blue', 8, 3.8, 'https://your-store.example/phone/oppo-reno-11---ocean-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('OnePlus Nord 3 - Rose Gold (6GB)', 'OnePlus', 59999, 73170, 'Snapdragon 7+ Gen 2', '6GB', '256GB', 'Rose Gold', 30, 4.4, 'https://your-store.example/phone/oneplus-nord-3---rose-gold-6gb', 'Available at select Croma and Reliance Digital stores'),
    ('Oppo Reno 10 - Ocean Blue', 'Oppo', 25999, 31710, 'Dimensity 7050', '6GB', '1TB', 'Ocean Blue', 30, 3.7, 'https://your-store.example/phone/oppo-reno-10---ocean-blue', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy S23 - Sunset Orange', 'Samsung', 69999, 76090, 'Exynos 2200', '16GB', '128GB', 'Sunset Orange', 0, 3.7, 'https://your-store.example/phone/galaxy-s23---sunset-orange', 'Available at flagship brand stores only'),
    ('Nothing Phone (1) - Titanium Gray (8GB)', 'Nothing', 49999, 66670, 'Snapdragon 778G+', '8GB', '256GB', 'Titanium Gray', 5, 4.7, 'https://your-store.example/phone/nothing-phone-1---titanium-gray-8gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Pixel 7 - Storm Silver', 'Google', 59999, 70590, 'Tensor G3', '16GB', '128GB', 'Storm Silver', 8, 3.9, 'https://your-store.example/phone/pixel-7---storm-silver', 'Available at select Croma and Reliance Digital stores'),
    ('Pixel 7 Pro - Sunset Orange', 'Google', 39999, 50000, 'Tensor G3', '6GB', '1TB', 'Sunset Orange', 5, 3.5, 'https://your-store.example/phone/pixel-7-pro---sunset-orange', 'In stock at authorized brand stores in major cities'),
    ('iPhone 15 Pro Max - Storm Silver', 'Apple', 59999, 66670, 'Apple A17 Pro', '12GB', '512GB', 'Storm Silver', 0, 3.6, 'https://your-store.example/phone/iphone-15-pro-max---storm-silver', 'Not available in offline stores'),
    ('iPhone 14 Plus - Sunset Orange', 'Apple', 139999, 164700, 'Apple A16 Bionic', '4GB', '64GB', 'Sunset Orange', 30, 4.7, 'https://your-store.example/phone/iphone-14-plus---sunset-orange', 'Not available in offline stores'),
    ('Galaxy Z Flip 5 - Pearl White (6GB)', 'Samsung', 18999, 23750, 'Exynos 2200', '6GB', '128GB', 'Pearl White', 0, 4.8, 'https://your-store.example/phone/galaxy-z-flip-5---pearl-white-6gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Vivo V30 - Sunset Orange', 'Vivo', 15999, 16840, 'Snapdragon 8 Gen 2', '4GB', '64GB', 'Sunset Orange', 5, 4.3, 'https://your-store.example/phone/vivo-v30---sunset-orange', 'Available at select Croma and Reliance Digital stores'),
    ('Nothing Phone (2) - Rose Gold', 'Nothing', 21999, 21999, 'Snapdragon 8+ Gen 1', '16GB', '512GB', 'Rose Gold', 0, 3.5, 'https://your-store.example/phone/nothing-phone-2---rose-gold', 'Available at flagship brand stores only'),
    ('Oppo F23 - Pearl White', 'Oppo', 59999, 59999, 'Snapdragon 695', '6GB', '1TB', 'Pearl White', 0, 4.2, 'https://your-store.example/phone/oppo-f23---pearl-white', 'Not available in offline stores'),
    ('Xiaomi 14 - Rose Gold', 'Xiaomi', 49999, 62500, 'Snapdragon 8 Gen 2', '6GB', '512GB', 'Rose Gold', 5, 4.2, 'https://your-store.example/phone/xiaomi-14---rose-gold', 'Available at select Croma and Reliance Digital stores'),
    ('iPhone SE (2024) - Storm Silver', 'Apple', 44999, 54880, 'Apple A15 Bionic', '4GB', '128GB', 'Storm Silver', 15, 3.5, 'https://your-store.example/phone/iphone-se-2024---storm-silver', 'In stock at authorized brand stores in major cities'),
    ('Vivo Y200 - Storm Silver (12GB)', 'Vivo', 54999, 62500, 'Snapdragon 778G', '12GB', '64GB', 'Storm Silver', 15, 3.9, 'https://your-store.example/phone/vivo-y200---storm-silver-12gb', 'Not available in offline stores'),
    ('iPhone 15 Pro - Pearl White', 'Apple', 9999, 10870, 'Apple A16 Bionic', '16GB', '64GB', 'Pearl White', 20, 4.9, 'https://your-store.example/phone/iphone-15-pro---pearl-white', 'Available at Vijay Sales outlets nationwide'),
    ('iPhone 15 - Pearl White', 'Apple', 34999, 38890, 'Apple A16 Bionic', '6GB', '256GB', 'Pearl White', 0, 4.8, 'https://your-store.example/phone/iphone-15---pearl-white', 'Not available in offline stores'),
    ('Realme Narzo 60 - Ocean Blue', 'Realme', 34999, 46670, 'Dimensity 7050', '12GB', '64GB', 'Ocean Blue', 2, 4.8, 'https://your-store.example/phone/realme-narzo-60---ocean-blue', 'Available at select Croma and Reliance Digital stores'),
    ('POCO F5 - Pearl White (6GB)', 'Xiaomi', 9999, 9999, 'Snapdragon 8 Gen 2', '6GB', '512GB', 'Pearl White', 0, 3.7, 'https://your-store.example/phone/poco-f5---pearl-white-6gb', 'Not available in offline stores'),
    ('Galaxy S24 - Forest Green', 'Samsung', 18999, 20650, 'Exynos 2200', '6GB', '256GB', 'Forest Green', 2, 4.4, 'https://your-store.example/phone/galaxy-s24---forest-green', 'Available at flagship brand stores only'),
    ('Redmi Note 13 - Sunset Orange', 'Xiaomi', 12999, 14770, 'Dimensity 7200', '12GB', '256GB', 'Sunset Orange', 20, 3.7, 'https://your-store.example/phone/redmi-note-13---sunset-orange', 'Available at select Croma and Reliance Digital stores'),
    ('POCO X6 - Titanium Gray', 'Xiaomi', 39999, 39999, 'Snapdragon 7 Gen 1', '8GB', '512GB', 'Titanium Gray', 30, 4.8, 'https://your-store.example/phone/poco-x6---titanium-gray', 'In stock at authorized brand stores in major cities'),
    ('Realme 11x - Storm Silver (12GB)', 'Realme', 54999, 54999, 'Dimensity 7050', '12GB', '64GB', 'Storm Silver', 20, 3.7, 'https://your-store.example/phone/realme-11x---storm-silver-12gb', 'Available at flagship brand stores only');

-- LAPTOPS (100)
INSERT INTO laptop
    (name, brand, price, mrp, processor, ram, storage, color, units_available, rating, online_link, offline_availability)
VALUES
    ('TUF Gaming A15 - Shadow Black', 'Asus', 124999, 152440, 'Intel Core i9-13900H', '16GB', '2TB SSD', 'Shadow Black', 2, 4.8, 'https://your-store.example/laptop/tuf-gaming-a15---shadow-black', 'In stock at authorized brand stores in major cities'),
    ('Zenbook 14 OLED - Silver', 'Asus', 79999, 90910, 'Intel Core i7-13700H', '32GB', '512GB SSD', 'Silver', 12, 4.1, 'https://your-store.example/laptop/zenbook-14-oled---silver', 'Available at flagship brand stores only'),
    ('Omen 16 - Silver', 'HP', 159999, 173910, 'Intel Core i7-1355U', '16GB', '512GB SSD', 'Silver', 15, 3.5, 'https://your-store.example/laptop/omen-16---silver', 'Available at select Croma and Reliance Digital stores'),
    ('Vivobook 15 - Shadow Black', 'Asus', 179999, 179999, 'AMD Ryzen 9 7940HS', '8GB', '2TB SSD', 'Shadow Black', 0, 3.8, 'https://your-store.example/laptop/vivobook-15---shadow-black', 'Available at select Croma and Reliance Digital stores'),
    ('Inspiron 14 Plus - Space Gray', 'Dell', 49999, 52630, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Space Gray', 5, 3.6, 'https://your-store.example/laptop/inspiron-14-plus---space-gray', 'Not available in offline stores'),
    ('MacBook Pro 16 (M3 Pro) - Moonlight White', 'Apple', 69999, 77780, 'Apple M3 Pro', '32GB', '256GB SSD', 'Moonlight White', 8, 3.8, 'https://your-store.example/laptop/macbook-pro-16-m3-pro---moonlight-white', 'Available at Vijay Sales outlets nationwide'),
    ('Yoga Slim 7 - Ponder Blue', 'Lenovo', 74999, 81520, 'AMD Ryzen 5 7530U', '8GB', '2TB SSD', 'Ponder Blue', 2, 3.8, 'https://your-store.example/laptop/yoga-slim-7---ponder-blue', 'In stock at authorized brand stores in major cities'),
    ('Stealth 14 - Ponder Blue', 'MSI', 199999, 235290, 'Intel Core i7-13700H', '16GB', '256GB SSD', 'Ponder Blue', 8, 4.9, 'https://your-store.example/laptop/stealth-14---ponder-blue', 'Available at flagship brand stores only'),
    ('IdeaPad Gaming 3 - Moonlight White', 'Lenovo', 69999, 69999, 'Intel Core i5-1335U', '32GB', '2TB SSD', 'Moonlight White', 0, 3.4, 'https://your-store.example/laptop/ideapad-gaming-3---moonlight-white', 'In stock at authorized brand stores in major cities'),
    ('Legion 5 Pro - Cobalt Blue', 'Lenovo', 124999, 135870, 'AMD Ryzen 5 7530U', '8GB', '1TB SSD', 'Cobalt Blue', 0, 3.5, 'https://your-store.example/laptop/legion-5-pro---cobalt-blue', 'Available at flagship brand stores only'),
    ('Cyborg 15 - Cobalt Blue', 'MSI', 199999, 250000, 'Intel Core i7-13700H', '8GB', '1TB SSD', 'Cobalt Blue', 2, 4.1, 'https://your-store.example/laptop/cyborg-15---cobalt-blue', 'Available at Vijay Sales outlets nationwide'),
    ('Victus 15 - Cobalt Blue', 'HP', 34999, 38040, 'Intel Core i5-1335U', '32GB', '1TB SSD', 'Cobalt Blue', 0, 4.0, 'https://your-store.example/laptop/victus-15---cobalt-blue', 'In stock at authorized brand stores in major cities'),
    ('Pavilion 15 - Silver', 'HP', 64999, 64999, 'AMD Ryzen 5 7530U', '8GB', '512GB SSD', 'Silver', 12, 4.0, 'https://your-store.example/laptop/pavilion-15---silver', 'Available at Vijay Sales outlets nationwide'),
    ('XPS 15 - Space Gray', 'Dell', 79999, 97560, 'Intel Core i5-1335U', '8GB', '256GB SSD', 'Space Gray', 30, 4.1, 'https://your-store.example/laptop/xps-15---space-gray', 'Not available in offline stores'),
    ('Spectre x360 - Silver', 'HP', 99999, 105260, 'Intel Core i7-1355U', '32GB', '256GB SSD', 'Silver', 15, 4.4, 'https://your-store.example/laptop/spectre-x360---silver', 'Not available in offline stores'),
    ('MacBook Air 15 (M3) - Ponder Blue', 'Apple', 79999, 106670, 'Apple M3', '8GB', '1TB SSD', 'Ponder Blue', 12, 4.0, 'https://your-store.example/laptop/macbook-air-15-m3---ponder-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Alienware m16 - Cobalt Blue', 'Dell', 94999, 111760, 'Intel Core i9-13900H', '8GB', '2TB SSD', 'Cobalt Blue', 5, 4.8, 'https://your-store.example/laptop/alienware-m16---cobalt-blue', 'Not available in offline stores'),
    ('Vostro 15 - Space Gray', 'Dell', 109999, 146670, 'Intel Core i5-1335U', '8GB', '2TB SSD', 'Space Gray', 12, 4.1, 'https://your-store.example/laptop/vostro-15---space-gray', 'In stock at authorized brand stores in major cities'),
    ('ROG Zephyrus G14 - Space Gray', 'Asus', 34999, 41180, 'AMD Ryzen 7 7730U', '32GB', '512GB SSD', 'Space Gray', 0, 4.3, 'https://your-store.example/laptop/rog-zephyrus-g14---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Inspiron 15 - Graphite', 'Dell', 159999, 177780, 'Intel Core i5-1335U', '8GB', '1TB SSD', 'Graphite', 2, 4.2, 'https://your-store.example/laptop/inspiron-15---graphite', 'Available at select Croma and Reliance Digital stores'),
    ('XPS 13 - Silver', 'Dell', 99999, 105260, 'Intel Core i7-13700H', '8GB', '1TB SSD', 'Silver', 0, 4.9, 'https://your-store.example/laptop/xps-13---silver', 'Not available in offline stores'),
    ('Galaxy Book3 360 - Ponder Blue', 'Samsung', 39999, 43480, 'Intel Core i7-1355U', '8GB', '512GB SSD', 'Ponder Blue', 45, 4.0, 'https://your-store.example/laptop/galaxy-book3-360---ponder-blue', 'In stock at authorized brand stores in major cities'),
    ('Envy 14 - Cobalt Blue', 'HP', 139999, 139999, 'Intel Core i7-1355U', '32GB', '512GB SSD', 'Cobalt Blue', 15, 4.8, 'https://your-store.example/laptop/envy-14---cobalt-blue', 'In stock at authorized brand stores in major cities'),
    ('ThinkPad X1 Carbon - Shadow Black', 'Lenovo', 94999, 103260, 'Intel Core i5-1335U', '8GB', '512GB SSD', 'Shadow Black', 0, 4.7, 'https://your-store.example/laptop/thinkpad-x1-carbon---shadow-black', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Modern 14 - Silver', 'MSI', 89999, 112500, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Silver', 8, 4.4, 'https://your-store.example/laptop/modern-14---silver', 'Available at Vijay Sales outlets nationwide'),
    ('Nitro 5 - Moonlight White', 'Acer', 69999, 85360, 'AMD Ryzen 5 7530U', '16GB', '1TB SSD', 'Moonlight White', 30, 4.1, 'https://your-store.example/laptop/nitro-5---moonlight-white', 'Available at select Croma and Reliance Digital stores'),
    ('Katana 15 - Silver', 'MSI', 139999, 186670, 'Intel Core i9-13900H', '8GB', '2TB SSD', 'Silver', 20, 4.7, 'https://your-store.example/laptop/katana-15---silver', 'Not available in offline stores'),
    ('Galaxy Book3 Pro - Shadow Black', 'Samsung', 49999, 58820, 'Intel Core i5-1335U', '8GB', '1TB SSD', 'Shadow Black', 12, 3.5, 'https://your-store.example/laptop/galaxy-book3-pro---shadow-black', 'Not available in offline stores'),
    ('Aspire Vero - Moonlight White', 'Acer', 159999, 168420, 'Intel Core i7-13700H', '8GB', '256GB SSD', 'Moonlight White', 0, 4.8, 'https://your-store.example/laptop/aspire-vero---moonlight-white', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy Book3 - Cobalt Blue', 'Samsung', 159999, 168420, 'Intel Core i5-1335U', '8GB', '2TB SSD', 'Cobalt Blue', 0, 4.7, 'https://your-store.example/laptop/galaxy-book3---cobalt-blue', 'Available at flagship brand stores only'),
    ('Swift Go 14 - Graphite', 'Acer', 49999, 55550, 'Intel Core i5-1335U', '8GB', '2TB SSD', 'Graphite', 2, 4.4, 'https://your-store.example/laptop/swift-go-14---graphite', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('ThinkPad E14 - Space Gray', 'Lenovo', 44999, 47370, 'AMD Ryzen 5 7530U', '32GB', '1TB SSD', 'Space Gray', 12, 4.7, 'https://your-store.example/laptop/thinkpad-e14---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Predator Helios 16 - Cobalt Blue', 'Acer', 124999, 135870, 'Intel Core i5-1335U', '16GB', '2TB SSD', 'Cobalt Blue', 45, 3.8, 'https://your-store.example/laptop/predator-helios-16---cobalt-blue', 'Available at flagship brand stores only'),
    ('Pavilion x360 - Space Gray', 'HP', 89999, 94740, 'AMD Ryzen 5 7530U', '8GB', '512GB SSD', 'Space Gray', 15, 3.6, 'https://your-store.example/laptop/pavilion-x360---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('MacBook Pro 14 (M3) - Graphite', 'Apple', 89999, 89999, 'Apple M3', '8GB', '1TB SSD', 'Graphite', 30, 3.5, 'https://your-store.example/laptop/macbook-pro-14-m3---graphite', 'Available at Vijay Sales outlets nationwide'),
    ('Aspire 5 - Cobalt Blue', 'Acer', 124999, 138890, 'Intel Core i7-13700H', '32GB', '256GB SSD', 'Cobalt Blue', 30, 4.3, 'https://your-store.example/laptop/aspire-5---cobalt-blue', 'Not available in offline stores'),
    ('ROG Strix G16 - Graphite', 'Asus', 94999, 126670, 'AMD Ryzen 9 7940HS', '16GB', '1TB SSD', 'Graphite', 2, 3.9, 'https://your-store.example/laptop/rog-strix-g16---graphite', 'Available at select Croma and Reliance Digital stores'),
    ('IdeaPad Slim 5 - Shadow Black', 'Lenovo', 69999, 77780, 'Intel Core i7-13700H', '32GB', '256GB SSD', 'Shadow Black', 30, 3.8, 'https://your-store.example/laptop/ideapad-slim-5---shadow-black', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('MacBook Air 13 (M2) - Cobalt Blue', 'Apple', 199999, 199999, 'Apple M3 Pro', '16GB', '256GB SSD', 'Cobalt Blue', 5, 3.6, 'https://your-store.example/laptop/macbook-air-13-m2---cobalt-blue', 'Available at flagship brand stores only'),
    ('TUF Gaming A15 - Graphite', 'Asus', 109999, 109999, 'Intel Core i9-13900H', '32GB', '1TB SSD', 'Graphite', 2, 4.1, 'https://your-store.example/laptop/tuf-gaming-a15---graphite', 'Available at flagship brand stores only'),
    ('Zenbook 14 OLED - Graphite', 'Asus', 39999, 53330, 'AMD Ryzen 7 7730U', '8GB', '256GB SSD', 'Graphite', 12, 3.9, 'https://your-store.example/laptop/zenbook-14-oled---graphite', 'Available at flagship brand stores only'),
    ('Omen 16 - Ponder Blue', 'HP', 179999, 240000, 'Intel Core i7-1355U', '16GB', '1TB SSD', 'Ponder Blue', 2, 3.7, 'https://your-store.example/laptop/omen-16---ponder-blue', 'Available at flagship brand stores only'),
    ('Vivobook 15 - Cobalt Blue', 'Asus', 139999, 152170, 'Intel Core i7-13700H', '8GB', '256GB SSD', 'Cobalt Blue', 2, 4.1, 'https://your-store.example/laptop/vivobook-15---cobalt-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Inspiron 14 Plus - Graphite', 'Dell', 54999, 61110, 'Intel Core i9-13900H', '16GB', '2TB SSD', 'Graphite', 0, 3.5, 'https://your-store.example/laptop/inspiron-14-plus---graphite', 'Available at flagship brand stores only'),
    ('MacBook Pro 16 (M3 Pro) - Ponder Blue', 'Apple', 199999, 217390, 'Apple M3', '32GB', '2TB SSD', 'Ponder Blue', 2, 4.8, 'https://your-store.example/laptop/macbook-pro-16-m3-pro---ponder-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Yoga Slim 7 - Silver', 'Lenovo', 179999, 195650, 'Intel Core i5-1335U', '16GB', '512GB SSD', 'Silver', 2, 3.5, 'https://your-store.example/laptop/yoga-slim-7---silver', 'Available at select Croma and Reliance Digital stores'),
    ('Stealth 14 - Silver', 'MSI', 179999, 211760, 'AMD Ryzen 7 7730U', '8GB', '512GB SSD', 'Silver', 5, 4.2, 'https://your-store.example/laptop/stealth-14---silver', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('IdeaPad Gaming 3 - Moonlight White (32GB)', 'Lenovo', 109999, 109999, 'Intel Core i7-13700H', '32GB', '1TB SSD', 'Moonlight White', 8, 4.3, 'https://your-store.example/laptop/ideapad-gaming-3---moonlight-white-32gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Legion 5 Pro - Cobalt Blue (16GB)', 'Lenovo', 139999, 170730, 'Intel Core i5-1335U', '16GB', '2TB SSD', 'Cobalt Blue', 0, 4.5, 'https://your-store.example/laptop/legion-5-pro---cobalt-blue-16gb', 'Not available in offline stores'),
    ('Cyborg 15 - Space Gray', 'MSI', 69999, 69999, 'Intel Core i7-13700H', '16GB', '512GB SSD', 'Space Gray', 0, 3.9, 'https://your-store.example/laptop/cyborg-15---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Victus 15 - Graphite', 'HP', 74999, 93750, 'Intel Core i5-1335U', '16GB', '2TB SSD', 'Graphite', 8, 3.8, 'https://your-store.example/laptop/victus-15---graphite', 'In stock at authorized brand stores in major cities'),
    ('Pavilion 15 - Silver (8GB)', 'HP', 159999, 173910, 'Intel Core i5-1335U', '8GB', '1TB SSD', 'Silver', 5, 4.8, 'https://your-store.example/laptop/pavilion-15---silver-8gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('XPS 15 - Ponder Blue', 'Dell', 64999, 76470, 'Intel Core i7-13700H', '16GB', '512GB SSD', 'Ponder Blue', 30, 4.1, 'https://your-store.example/laptop/xps-15---ponder-blue', 'Available at flagship brand stores only'),
    ('Spectre x360 - Graphite', 'HP', 34999, 46670, 'Intel Core i5-1335U', '16GB', '512GB SSD', 'Graphite', 8, 4.6, 'https://your-store.example/laptop/spectre-x360---graphite', 'Not available in offline stores'),
    ('MacBook Air 15 (M3) - Moonlight White', 'Apple', 199999, 210530, 'Apple M2', '32GB', '512GB SSD', 'Moonlight White', 0, 3.4, 'https://your-store.example/laptop/macbook-air-15-m3---moonlight-white', 'Available at select Croma and Reliance Digital stores'),
    ('Alienware m16 - Moonlight White', 'Dell', 59999, 59999, 'Intel Core i7-13700H', '8GB', '256GB SSD', 'Moonlight White', 0, 3.6, 'https://your-store.example/laptop/alienware-m16---moonlight-white', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Vostro 15 - Graphite', 'Dell', 39999, 39999, 'Intel Core i9-13900H', '8GB', '256GB SSD', 'Graphite', 45, 4.5, 'https://your-store.example/laptop/vostro-15---graphite', 'In stock at authorized brand stores in major cities'),
    ('ROG Zephyrus G14 - Cobalt Blue', 'Asus', 179999, 179999, 'AMD Ryzen 7 7730U', '32GB', '2TB SSD', 'Cobalt Blue', 5, 3.7, 'https://your-store.example/laptop/rog-zephyrus-g14---cobalt-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Inspiron 15 - Silver', 'Dell', 39999, 48780, 'Intel Core i9-13900H', '8GB', '1TB SSD', 'Silver', 0, 3.6, 'https://your-store.example/laptop/inspiron-15---silver', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('XPS 13 - Space Gray', 'Dell', 79999, 88890, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Space Gray', 0, 3.9, 'https://your-store.example/laptop/xps-13---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy Book3 360 - Silver', 'Samsung', 94999, 105550, 'Intel Core i7-1355U', '32GB', '2TB SSD', 'Silver', 45, 4.5, 'https://your-store.example/laptop/galaxy-book3-360---silver', 'Not available in offline stores'),
    ('Envy 14 - Silver', 'HP', 109999, 109999, 'Intel Core i5-1335U', '16GB', '2TB SSD', 'Silver', 30, 4.2, 'https://your-store.example/laptop/envy-14---silver', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('ThinkPad X1 Carbon - Cobalt Blue', 'Lenovo', 44999, 44999, 'AMD Ryzen 5 7530U', '8GB', '2TB SSD', 'Cobalt Blue', 30, 3.7, 'https://your-store.example/laptop/thinkpad-x1-carbon---cobalt-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Modern 14 - Silver (8GB)', 'MSI', 94999, 100000, 'Intel Core i9-13900H', '8GB', '2TB SSD', 'Silver', 20, 4.3, 'https://your-store.example/laptop/modern-14---silver-8gb', 'Available at flagship brand stores only'),
    ('Nitro 5 - Ponder Blue', 'Acer', 199999, 217390, 'Intel Core i5-1335U', '16GB', '512GB SSD', 'Ponder Blue', 20, 3.6, 'https://your-store.example/laptop/nitro-5---ponder-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Katana 15 - Cobalt Blue', 'MSI', 44999, 51140, 'Intel Core i9-13900H', '32GB', '256GB SSD', 'Cobalt Blue', 12, 3.5, 'https://your-store.example/laptop/katana-15---cobalt-blue', 'Not available in offline stores'),
    ('Galaxy Book3 Pro - Graphite', 'Samsung', 44999, 51140, 'Intel Core i7-1355U', '32GB', '256GB SSD', 'Graphite', 5, 3.9, 'https://your-store.example/laptop/galaxy-book3-pro---graphite', 'Not available in offline stores'),
    ('Aspire Vero - Moonlight White (16GB)', 'Acer', 159999, 195120, 'Intel Core i5-1335U', '16GB', '512GB SSD', 'Moonlight White', 2, 4.2, 'https://your-store.example/laptop/aspire-vero---moonlight-white-16gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Galaxy Book3 - Cobalt Blue (32GB)', 'Samsung', 39999, 50000, 'Intel Core i7-1355U', '32GB', '1TB SSD', 'Cobalt Blue', 2, 4.7, 'https://your-store.example/laptop/galaxy-book3---cobalt-blue-32gb', 'Not available in offline stores'),
    ('Swift Go 14 - Graphite (16GB)', 'Acer', 179999, 219510, 'Intel Core i7-13700H', '16GB', '512GB SSD', 'Graphite', 20, 4.4, 'https://your-store.example/laptop/swift-go-14---graphite-16gb', 'Available at Vijay Sales outlets nationwide'),
    ('ThinkPad E14 - Moonlight White', 'Lenovo', 69999, 76090, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Moonlight White', 30, 3.7, 'https://your-store.example/laptop/thinkpad-e14---moonlight-white', 'Available at Vijay Sales outlets nationwide'),
    ('Predator Helios 16 - Cobalt Blue (8GB)', 'Acer', 54999, 62500, 'Intel Core i7-13700H', '8GB', '512GB SSD', 'Cobalt Blue', 45, 4.2, 'https://your-store.example/laptop/predator-helios-16---cobalt-blue-8gb', 'In stock at authorized brand stores in major cities'),
    ('Pavilion x360 - Space Gray (16GB)', 'HP', 89999, 94740, 'Intel Core i7-1355U', '16GB', '256GB SSD', 'Space Gray', 0, 3.7, 'https://your-store.example/laptop/pavilion-x360---space-gray-16gb', 'In stock at authorized brand stores in major cities'),
    ('MacBook Pro 14 (M3) - Space Gray', 'Apple', 79999, 88890, 'Apple M3 Pro', '16GB', '2TB SSD', 'Space Gray', 5, 3.6, 'https://your-store.example/laptop/macbook-pro-14-m3---space-gray', 'Available at select Croma and Reliance Digital stores'),
    ('Aspire 5 - Ponder Blue', 'Acer', 64999, 64999, 'AMD Ryzen 5 7530U', '16GB', '256GB SSD', 'Ponder Blue', 15, 4.7, 'https://your-store.example/laptop/aspire-5---ponder-blue', 'Not available in offline stores'),
    ('ROG Strix G16 - Graphite (16GB)', 'Asus', 69999, 73680, 'AMD Ryzen 9 7940HS', '16GB', '256GB SSD', 'Graphite', 8, 4.3, 'https://your-store.example/laptop/rog-strix-g16---graphite-16gb', 'Not available in offline stores'),
    ('IdeaPad Slim 5 - Silver', 'Lenovo', 69999, 76090, 'AMD Ryzen 9 7940HS', '32GB', '2TB SSD', 'Silver', 45, 4.7, 'https://your-store.example/laptop/ideapad-slim-5---silver', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('MacBook Air 13 (M2) - Space Gray', 'Apple', 49999, 55550, 'Apple M3', '16GB', '1TB SSD', 'Space Gray', 0, 4.7, 'https://your-store.example/laptop/macbook-air-13-m2---space-gray', 'In stock at authorized brand stores in major cities'),
    ('TUF Gaming A15 - Cobalt Blue', 'Asus', 99999, 121950, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Cobalt Blue', 20, 3.4, 'https://your-store.example/laptop/tuf-gaming-a15---cobalt-blue', 'Not available in offline stores'),
    ('Zenbook 14 OLED - Moonlight White', 'Asus', 59999, 73170, 'AMD Ryzen 9 7940HS', '8GB', '2TB SSD', 'Moonlight White', 0, 3.5, 'https://your-store.example/laptop/zenbook-14-oled---moonlight-white', 'Available at flagship brand stores only'),
    ('Omen 16 - Space Gray', 'HP', 59999, 59999, 'Intel Core i7-1355U', '32GB', '1TB SSD', 'Space Gray', 45, 4.1, 'https://your-store.example/laptop/omen-16---space-gray', 'In stock at authorized brand stores in major cities'),
    ('Vivobook 15 - Graphite', 'Asus', 139999, 175000, 'AMD Ryzen 7 7730U', '32GB', '1TB SSD', 'Graphite', 12, 4.0, 'https://your-store.example/laptop/vivobook-15---graphite', 'Not available in offline stores'),
    ('Inspiron 14 Plus - Space Gray (32GB)', 'Dell', 59999, 80000, 'Intel Core i7-13700H', '32GB', '256GB SSD', 'Space Gray', 12, 4.4, 'https://your-store.example/laptop/inspiron-14-plus---space-gray-32gb', 'Available at Vijay Sales outlets nationwide'),
    ('MacBook Pro 16 (M3 Pro) - Ponder Blue (8GB)', 'Apple', 99999, 99999, 'Apple M3', '8GB', '256GB SSD', 'Ponder Blue', 15, 4.8, 'https://your-store.example/laptop/macbook-pro-16-m3-pro---ponder-blue-8gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Yoga Slim 7 - Graphite', 'Lenovo', 94999, 105550, 'AMD Ryzen 5 7530U', '8GB', '512GB SSD', 'Graphite', 15, 4.8, 'https://your-store.example/laptop/yoga-slim-7---graphite', 'Available at flagship brand stores only'),
    ('Stealth 14 - Space Gray', 'MSI', 99999, 105260, 'Intel Core i9-13900H', '8GB', '512GB SSD', 'Space Gray', 0, 4.6, 'https://your-store.example/laptop/stealth-14---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('IdeaPad Gaming 3 - Space Gray', 'Lenovo', 139999, 164700, 'Intel Core i7-13700H', '8GB', '1TB SSD', 'Space Gray', 20, 4.9, 'https://your-store.example/laptop/ideapad-gaming-3---space-gray', 'Available at flagship brand stores only'),
    ('Legion 5 Pro - Graphite', 'Lenovo', 54999, 61110, 'AMD Ryzen 9 7940HS', '16GB', '512GB SSD', 'Graphite', 15, 4.4, 'https://your-store.example/laptop/legion-5-pro---graphite', 'Not available in offline stores'),
    ('Cyborg 15 - Graphite', 'MSI', 59999, 68180, 'Intel Core i9-13900H', '8GB', '1TB SSD', 'Graphite', 5, 4.4, 'https://your-store.example/laptop/cyborg-15---graphite', 'Available at Vijay Sales outlets nationwide'),
    ('Victus 15 - Shadow Black', 'HP', 139999, 159090, 'AMD Ryzen 7 7730U', '32GB', '256GB SSD', 'Shadow Black', 2, 4.8, 'https://your-store.example/laptop/victus-15---shadow-black', 'Not available in offline stores'),
    ('XPS 15 - Graphite', 'Dell', 199999, 217390, 'Intel Core i5-1335U', '32GB', '256GB SSD', 'Graphite', 0, 4.4, 'https://your-store.example/laptop/xps-15---graphite', 'Available at Vijay Sales outlets nationwide'),
    ('Spectre x360 - Moonlight White', 'HP', 49999, 60970, 'Intel Core i7-1355U', '8GB', '512GB SSD', 'Moonlight White', 12, 4.6, 'https://your-store.example/laptop/spectre-x360---moonlight-white', 'In stock at authorized brand stores in major cities'),
    ('MacBook Air 15 (M3) - Shadow Black', 'Apple', 179999, 225000, 'Apple M2', '32GB', '256GB SSD', 'Shadow Black', 8, 3.7, 'https://your-store.example/laptop/macbook-air-15-m3---shadow-black', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Alienware m16 - Space Gray', 'Dell', 159999, 159999, 'Intel Core i5-1335U', '32GB', '2TB SSD', 'Space Gray', 30, 3.6, 'https://your-store.example/laptop/alienware-m16---space-gray', 'Not available in offline stores'),
    ('Vostro 15 - Space Gray (16GB)', 'Dell', 54999, 67070, 'Intel Core i7-13700H', '16GB', '256GB SSD', 'Space Gray', 20, 4.8, 'https://your-store.example/laptop/vostro-15---space-gray-16gb', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('ROG Zephyrus G14 - Shadow Black', 'Asus', 69999, 73680, 'Intel Core i9-13900H', '8GB', '256GB SSD', 'Shadow Black', 12, 4.1, 'https://your-store.example/laptop/rog-zephyrus-g14---shadow-black', 'Available at flagship brand stores only'),
    ('Inspiron 15 - Shadow Black', 'Dell', 79999, 94120, 'Intel Core i7-13700H', '16GB', '2TB SSD', 'Shadow Black', 0, 3.7, 'https://your-store.example/laptop/inspiron-15---shadow-black', 'Available at Vijay Sales outlets nationwide'),
    ('XPS 13 - Graphite', 'Dell', 34999, 39770, 'Intel Core i5-1335U', '32GB', '256GB SSD', 'Graphite', 0, 4.2, 'https://your-store.example/laptop/xps-13---graphite', 'Not available in offline stores'),
    ('Galaxy Book3 360 - Cobalt Blue', 'Samsung', 54999, 57890, 'Intel Core i5-1335U', '8GB', '2TB SSD', 'Cobalt Blue', 12, 3.5, 'https://your-store.example/laptop/galaxy-book3-360---cobalt-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Envy 14 - Ponder Blue', 'HP', 89999, 100000, 'AMD Ryzen 7 7730U', '32GB', '512GB SSD', 'Ponder Blue', 15, 3.9, 'https://your-store.example/laptop/envy-14---ponder-blue', 'Available at Vijay Sales outlets nationwide');

-- HEADPHONES (100)
INSERT INTO headphone
    (name, brand, price, mrp, type, quality, color, units_available, rating, online_link, offline_availability)
VALUES
    ('Live 660NC - Smoke White', 'JBL', 1999, 2670, 'Over-Ear Wireless', 'Bass-boosted signature', 'Smoke White', 0, 4.6, 'https://your-store.example/headphone/live-660nc---smoke-white', 'Available at flagship brand stores only'),
    ('WH-1000XM4 - Space Gray', 'Sony', 19999, 26670, 'Over-Ear Wired', 'Balanced sound with deep bass', 'Space Gray', 0, 3.7, 'https://your-store.example/headphone/wh-1000xm4---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Nirvana Ivory - Ivory', 'Boat', 29999, 29999, 'In-Ear Wireless Neckband', 'Balanced sound with deep bass', 'Ivory', 2, 4.7, 'https://your-store.example/headphone/nirvana-ivory---ivory', 'Not available in offline stores'),
    ('Accentum Wireless - Olive Green', 'Sennheiser', 2999, 3410, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Olive Green', 2, 4.6, 'https://your-store.example/headphone/accentum-wireless---olive-green', 'Available at flagship brand stores only'),
    ('Galaxy Buds2 Pro - Ivory', 'Samsung', 9999, 11760, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Ivory', 0, 3.9, 'https://your-store.example/headphone/galaxy-buds2-pro---ivory', 'Not available in offline stores'),
    ('WH-CH720N - Space Gray', 'Sony', 1999, 2500, 'On-Ear Wired', 'Crisp vocal clarity', 'Space Gray', 0, 4.6, 'https://your-store.example/headphone/wh-ch720n---space-gray', 'Not available in offline stores'),
    ('WH-1000XM5 - Space Gray', 'Sony', 19999, 19999, 'On-Ear Wired', 'Studio-grade audio', 'Space Gray', 15, 4.3, 'https://your-store.example/headphone/wh-1000xm5---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Tune 760NC - Midnight Black', 'JBL', 34999, 34999, 'On-Ear Wired', 'Crisp vocal clarity', 'Midnight Black', 0, 4.4, 'https://your-store.example/headphone/tune-760nc---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('Buds Pro 2 - Midnight Black', 'OnePlus', 1499, 1499, 'On-Ear Wired', 'Studio-grade audio', 'Midnight Black', 0, 4.9, 'https://your-store.example/headphone/buds-pro-2---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('HD 660S2 - Midnight Black', 'Sennheiser', 2999, 2999, 'Over-Ear Wireless', 'Bass-boosted signature', 'Midnight Black', 8, 4.5, 'https://your-store.example/headphone/hd-660s2---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('QuietComfort Ultra - Coral Red', 'Bose', 4499, 4740, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Coral Red', 0, 3.8, 'https://your-store.example/headphone/quietcomfort-ultra---coral-red', 'Available at flagship brand stores only'),
    ('QuietComfort 45 - Ivory', 'Bose', 34999, 38890, 'On-Ear Wired', 'Immersive spatial audio', 'Ivory', 0, 4.5, 'https://your-store.example/headphone/quietcomfort-45---ivory', 'Available at select Croma and Reliance Digital stores'),
    ('Rockerz 450 Pro - Smoke White', 'Boat', 1499, 2000, 'In-Ear Wireless Neckband', 'Immersive spatial audio', 'Smoke White', 0, 4.0, 'https://your-store.example/headphone/rockerz-450-pro---smoke-white', 'Available at Vijay Sales outlets nationwide'),
    ('Rockerz 550 - Ivory', 'Boat', 4499, 4499, 'On-Ear Wired', 'Crisp vocal clarity', 'Ivory', 12, 4.0, 'https://your-store.example/headphone/rockerz-550---ivory', 'Available at flagship brand stores only'),
    ('SoundLink Around-Ear - Ivory', 'Bose', 29999, 31580, 'On-Ear Wired', 'Immersive spatial audio', 'Ivory', 2, 4.8, 'https://your-store.example/headphone/soundlink-around-ear---ivory', 'Available at select Croma and Reliance Digital stores'),
    ('AirPods Pro 2 - Sky Blue', 'Apple', 4499, 5490, 'In-Ear Wireless Neckband', 'Bass-boosted signature', 'Sky Blue', 15, 4.6, 'https://your-store.example/headphone/airpods-pro-2---sky-blue', 'Not available in offline stores'),
    ('Indy ANC - Sky Blue', 'Skullcandy', 14999, 14999, 'In-Ear True Wireless', 'Audiophile-tuned clarity', 'Sky Blue', 45, 4.9, 'https://your-store.example/headphone/indy-anc---sky-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Crusher ANC 2 - Olive Green', 'Skullcandy', 14999, 14999, 'Over-Ear Wired', 'Immersive spatial audio', 'Olive Green', 2, 4.3, 'https://your-store.example/headphone/crusher-anc-2---olive-green', 'Available at Vijay Sales outlets nationwide'),
    ('Buds 3 - Space Gray', 'OnePlus', 24999, 29410, 'Over-Ear Wireless', 'Bass-boosted signature', 'Space Gray', 15, 4.3, 'https://your-store.example/headphone/buds-3---space-gray', 'In stock at authorized brand stores in major cities'),
    ('FreeBuds Pro 3 - Olive Green', 'Huawei', 29999, 29999, 'In-Ear True Wireless', 'Immersive spatial audio', 'Olive Green', 12, 3.8, 'https://your-store.example/headphone/freebuds-pro-3---olive-green', 'Not available in offline stores'),
    ('Galaxy Buds FE - Midnight Black', 'Samsung', 1999, 2670, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Midnight Black', 2, 3.8, 'https://your-store.example/headphone/galaxy-buds-fe---midnight-black', 'Available at flagship brand stores only'),
    ('HD 450BT - Ivory', 'Sennheiser', 34999, 34999, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Ivory', 30, 4.2, 'https://your-store.example/headphone/hd-450bt---ivory', 'Not available in offline stores'),
    ('WF-1000XM5 - Midnight Black', 'Sony', 7999, 7999, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Midnight Black', 15, 4.1, 'https://your-store.example/headphone/wf-1000xm5---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('AirPods 3 - Sky Blue', 'Apple', 1499, 1870, 'On-Ear Wired', 'Bass-boosted signature', 'Sky Blue', 0, 4.2, 'https://your-store.example/headphone/airpods-3---sky-blue', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy Buds3 - Olive Green', 'Samsung', 2499, 3330, 'Over-Ear Wireless', 'Bass-boosted signature', 'Olive Green', 30, 4.7, 'https://your-store.example/headphone/galaxy-buds3---olive-green', 'Available at flagship brand stores only'),
    ('LinkBuds S - Sky Blue', 'Sony', 34999, 38040, 'Over-Ear Wired', 'Crisp vocal clarity', 'Sky Blue', 5, 3.7, 'https://your-store.example/headphone/linkbuds-s---sky-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Club Pro+ TWS - Midnight Black', 'JBL', 12999, 17330, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Midnight Black', 12, 4.0, 'https://your-store.example/headphone/club-pro+-tws---midnight-black', 'Available at flagship brand stores only'),
    ('AirPods Max - Olive Green', 'Apple', 3499, 4270, 'Over-Ear Wireless', 'Studio-grade audio', 'Olive Green', 12, 4.7, 'https://your-store.example/headphone/airpods-max---olive-green', 'Available at Vijay Sales outlets nationwide'),
    ('AirPods 4 - Ivory', 'Apple', 29999, 34090, 'Active Noise Cancelling Over-Ear Wireless', 'Balanced sound with deep bass', 'Ivory', 45, 3.4, 'https://your-store.example/headphone/airpods-4---ivory', 'Available at Vijay Sales outlets nationwide'),
    ('Endurance Peak 3 - Space Gray', 'JBL', 1499, 1630, 'Active Noise Cancelling Over-Ear Wireless', 'Studio-grade audio', 'Space Gray', 45, 4.1, 'https://your-store.example/headphone/endurance-peak-3---space-gray', 'Available at flagship brand stores only'),
    ('Bullets Wireless Z2 - Midnight Black', 'OnePlus', 9999, 9999, 'In-Ear True Wireless', 'Bass-boosted signature', 'Midnight Black', 20, 4.6, 'https://your-store.example/headphone/bullets-wireless-z2---midnight-black', 'Available at flagship brand stores only'),
    ('Airdopes 141 - Midnight Black', 'Boat', 9999, 10870, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Midnight Black', 2, 4.0, 'https://your-store.example/headphone/airdopes-141---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('Hesh Evo - Smoke White', 'Skullcandy', 1999, 2440, 'Over-Ear Wired', 'Audiophile-tuned clarity', 'Smoke White', 20, 4.8, 'https://your-store.example/headphone/hesh-evo---smoke-white', 'Available at select Croma and Reliance Digital stores'),
    ('Momentum 4 - Olive Green', 'Sennheiser', 19999, 19999, 'Active Noise Cancelling Over-Ear Wireless', 'Immersive spatial audio', 'Olive Green', 8, 3.9, 'https://your-store.example/headphone/momentum-4---olive-green', 'In stock at authorized brand stores in major cities'),
    ('Sport Earbuds - Ivory', 'Bose', 2499, 2940, 'In-Ear Wireless Neckband', 'Crisp vocal clarity', 'Ivory', 2, 4.1, 'https://your-store.example/headphone/sport-earbuds---ivory', 'In stock at authorized brand stores in major cities'),
    ('FreeBuds 5i - Sky Blue', 'Huawei', 7999, 8420, 'In-Ear Wireless Neckband', 'Balanced sound with deep bass', 'Sky Blue', 0, 4.8, 'https://your-store.example/headphone/freebuds-5i---sky-blue', 'Available at Vijay Sales outlets nationwide'),
    ('Live 660NC - Smoke White (Studio-grade audio)', 'JBL', 49999, 55550, 'Active Noise Cancelling Over-Ear Wireless', 'Studio-grade audio', 'Smoke White', 30, 4.5, 'https://your-store.example/headphone/live-660nc---smoke-white-studio-grade-audio', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('WH-1000XM4 - Olive Green', 'Sony', 34999, 36840, 'Active Noise Cancelling Over-Ear Wireless', 'Studio-grade audio', 'Olive Green', 12, 4.5, 'https://your-store.example/headphone/wh-1000xm4---olive-green', 'In stock at authorized brand stores in major cities'),
    ('Nirvana Ivory - Ivory (Crisp vocal clarity)', 'Boat', 12999, 15850, 'Over-Ear Wired', 'Crisp vocal clarity', 'Ivory', 0, 4.1, 'https://your-store.example/headphone/nirvana-ivory---ivory-crisp-vocal-clarity', 'Available at Vijay Sales outlets nationwide'),
    ('Accentum Wireless - Sky Blue', 'Sennheiser', 19999, 24390, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Sky Blue', 15, 3.7, 'https://your-store.example/headphone/accentum-wireless---sky-blue', 'In stock at authorized brand stores in major cities'),
    ('Galaxy Buds2 Pro - Olive Green', 'Samsung', 3499, 4270, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Olive Green', 5, 4.6, 'https://your-store.example/headphone/galaxy-buds2-pro---olive-green', 'In stock at authorized brand stores in major cities'),
    ('WH-CH720N - Olive Green', 'Sony', 7999, 9090, 'Active Noise Cancelling Over-Ear Wireless', 'Crisp vocal clarity', 'Olive Green', 2, 4.6, 'https://your-store.example/headphone/wh-ch720n---olive-green', 'Available at select Croma and Reliance Digital stores'),
    ('WH-1000XM5 - Coral Red', 'Sony', 1499, 1830, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Coral Red', 12, 3.9, 'https://your-store.example/headphone/wh-1000xm5---coral-red', 'In stock at authorized brand stores in major cities'),
    ('Tune 760NC - Coral Red', 'JBL', 2999, 3160, 'In-Ear Wireless Neckband', 'Audiophile-tuned clarity', 'Coral Red', 12, 3.7, 'https://your-store.example/headphone/tune-760nc---coral-red', 'Available at select Croma and Reliance Digital stores'),
    ('Buds Pro 2 - Midnight Black (Balanced sound with deep bass)', 'OnePlus', 29999, 36580, 'Over-Ear Wired', 'Balanced sound with deep bass', 'Midnight Black', 2, 3.8, 'https://your-store.example/headphone/buds-pro-2---midnight-black-balanced-sound-with-deep-bass', 'Not available in offline stores'),
    ('HD 660S2 - Midnight Black (Audiophile-tuned clarity)', 'Sennheiser', 3499, 4670, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Midnight Black', 8, 3.9, 'https://your-store.example/headphone/hd-660s2---midnight-black-audiophile-tuned-clarity', 'In stock at authorized brand stores in major cities'),
    ('QuietComfort Ultra - Sky Blue', 'Bose', 34999, 42680, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Sky Blue', 20, 3.6, 'https://your-store.example/headphone/quietcomfort-ultra---sky-blue', 'Available at flagship brand stores only'),
    ('QuietComfort 45 - Smoke White', 'Bose', 5999, 6670, 'Over-Ear Wired', 'Bass-boosted signature', 'Smoke White', 0, 3.8, 'https://your-store.example/headphone/quietcomfort-45---smoke-white', 'In stock at authorized brand stores in major cities'),
    ('Rockerz 450 Pro - Sky Blue', 'Boat', 24999, 27170, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Sky Blue', 0, 4.0, 'https://your-store.example/headphone/rockerz-450-pro---sky-blue', 'Not available in offline stores'),
    ('Rockerz 550 - Midnight Black', 'Boat', 1999, 2100, 'In-Ear Wireless Neckband', 'Audiophile-tuned clarity', 'Midnight Black', 0, 4.1, 'https://your-store.example/headphone/rockerz-550---midnight-black', 'Available at flagship brand stores only'),
    ('SoundLink Around-Ear - Sky Blue', 'Bose', 39999, 39999, 'Over-Ear Wireless', 'Bass-boosted signature', 'Sky Blue', 30, 3.8, 'https://your-store.example/headphone/soundlink-around-ear---sky-blue', 'Available at Vijay Sales outlets nationwide'),
    ('AirPods Pro 2 - Coral Red', 'Apple', 1999, 2220, 'On-Ear Wired', 'Balanced sound with deep bass', 'Coral Red', 45, 3.7, 'https://your-store.example/headphone/airpods-pro-2---coral-red', 'In stock at authorized brand stores in major cities'),
    ('Indy ANC - Space Gray', 'Skullcandy', 7999, 8690, 'In-Ear Wireless Neckband', 'Balanced sound with deep bass', 'Space Gray', 45, 3.5, 'https://your-store.example/headphone/indy-anc---space-gray', 'Available at select Croma and Reliance Digital stores'),
    ('Crusher ANC 2 - Space Gray', 'Skullcandy', 34999, 38040, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Space Gray', 2, 4.3, 'https://your-store.example/headphone/crusher-anc-2---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Buds 3 - Ivory', 'OnePlus', 5999, 6520, 'Over-Ear Wired', 'Audiophile-tuned clarity', 'Ivory', 0, 3.5, 'https://your-store.example/headphone/buds-3---ivory', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('FreeBuds Pro 3 - Space Gray', 'Huawei', 24999, 31250, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Space Gray', 12, 3.9, 'https://your-store.example/headphone/freebuds-pro-3---space-gray', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('Galaxy Buds FE - Olive Green', 'Samsung', 34999, 41180, 'Active Noise Cancelling Over-Ear Wireless', 'Studio-grade audio', 'Olive Green', 20, 3.6, 'https://your-store.example/headphone/galaxy-buds-fe---olive-green', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('HD 450BT - Sky Blue', 'Sennheiser', 7999, 9090, 'Over-Ear Wireless', 'Crisp vocal clarity', 'Sky Blue', 0, 3.6, 'https://your-store.example/headphone/hd-450bt---sky-blue', 'Available at Vijay Sales outlets nationwide'),
    ('WF-1000XM5 - Space Gray', 'Sony', 1499, 1830, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Space Gray', 30, 3.5, 'https://your-store.example/headphone/wf-1000xm5---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('AirPods 3 - Ivory', 'Apple', 7999, 9410, 'In-Ear True Wireless', 'Immersive spatial audio', 'Ivory', 45, 4.5, 'https://your-store.example/headphone/airpods-3---ivory', 'Available at select Croma and Reliance Digital stores'),
    ('Galaxy Buds3 - Sky Blue', 'Samsung', 2999, 3660, 'In-Ear Wireless Neckband', 'Bass-boosted signature', 'Sky Blue', 30, 3.4, 'https://your-store.example/headphone/galaxy-buds3---sky-blue', 'Available at flagship brand stores only'),
    ('LinkBuds S - Midnight Black', 'Sony', 1499, 1630, 'Over-Ear Wireless', 'Studio-grade audio', 'Midnight Black', 45, 3.7, 'https://your-store.example/headphone/linkbuds-s---midnight-black', 'Available at select Croma and Reliance Digital stores'),
    ('Club Pro+ TWS - Sky Blue', 'JBL', 9999, 9999, 'Over-Ear Wired', 'Studio-grade audio', 'Sky Blue', 0, 4.8, 'https://your-store.example/headphone/club-pro+-tws---sky-blue', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('AirPods Max - Midnight Black', 'Apple', 9999, 13330, 'Active Noise Cancelling Over-Ear Wireless', 'Crisp vocal clarity', 'Midnight Black', 20, 4.2, 'https://your-store.example/headphone/airpods-max---midnight-black', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('AirPods 4 - Coral Red', 'Apple', 2999, 3160, 'In-Ear True Wireless', 'Studio-grade audio', 'Coral Red', 0, 3.8, 'https://your-store.example/headphone/airpods-4---coral-red', 'Not available in offline stores'),
    ('Endurance Peak 3 - Coral Red', 'JBL', 39999, 39999, 'In-Ear True Wireless', 'Studio-grade audio', 'Coral Red', 0, 4.0, 'https://your-store.example/headphone/endurance-peak-3---coral-red', 'In stock at authorized brand stores in major cities'),
    ('Bullets Wireless Z2 - Space Gray', 'OnePlus', 7999, 10670, 'Over-Ear Wireless', 'Balanced sound with deep bass', 'Space Gray', 20, 4.5, 'https://your-store.example/headphone/bullets-wireless-z2---space-gray', 'In stock at authorized brand stores in major cities'),
    ('Airdopes 141 - Olive Green', 'Boat', 1499, 1760, 'In-Ear Wireless Neckband', 'Bass-boosted signature', 'Olive Green', 45, 4.7, 'https://your-store.example/headphone/airdopes-141---olive-green', 'Available at flagship brand stores only'),
    ('Hesh Evo - Smoke White (Audiophile-tuned clarity)', 'Skullcandy', 19999, 22730, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Smoke White', 15, 3.8, 'https://your-store.example/headphone/hesh-evo---smoke-white-audiophile-tuned-clarity', 'Available at Vijay Sales outlets nationwide'),
    ('Momentum 4 - Ivory', 'Sennheiser', 24999, 29410, 'Over-Ear Wired', 'Audiophile-tuned clarity', 'Ivory', 30, 3.5, 'https://your-store.example/headphone/momentum-4---ivory', 'Available at flagship brand stores only'),
    ('Sport Earbuds - Midnight Black', 'Bose', 17999, 17999, 'Over-Ear Wireless', 'Bass-boosted signature', 'Midnight Black', 12, 3.6, 'https://your-store.example/headphone/sport-earbuds---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('FreeBuds 5i - Smoke White', 'Huawei', 14999, 18750, 'On-Ear Wired', 'Balanced sound with deep bass', 'Smoke White', 0, 3.7, 'https://your-store.example/headphone/freebuds-5i---smoke-white', 'Not available in offline stores'),
    ('Live 660NC - Coral Red', 'JBL', 29999, 29999, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Coral Red', 0, 4.7, 'https://your-store.example/headphone/live-660nc---coral-red', 'Available at flagship brand stores only'),
    ('WH-1000XM4 - Sky Blue', 'Sony', 9999, 9999, 'In-Ear Wireless Neckband', 'Crisp vocal clarity', 'Sky Blue', 45, 3.6, 'https://your-store.example/headphone/wh-1000xm4---sky-blue', 'Available at select Croma and Reliance Digital stores'),
    ('Nirvana Ivory - Space Gray', 'Boat', 1499, 1499, 'On-Ear Wired', 'Balanced sound with deep bass', 'Space Gray', 8, 3.6, 'https://your-store.example/headphone/nirvana-ivory---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Accentum Wireless - Ivory', 'Sennheiser', 4499, 6000, 'Active Noise Cancelling Over-Ear Wireless', 'Studio-grade audio', 'Ivory', 30, 4.8, 'https://your-store.example/headphone/accentum-wireless---ivory', 'Available at select Croma and Reliance Digital stores'),
    ('Galaxy Buds2 Pro - Coral Red', 'Samsung', 49999, 49999, 'Over-Ear Wireless', 'Bass-boosted signature', 'Coral Red', 30, 3.6, 'https://your-store.example/headphone/galaxy-buds2-pro---coral-red', 'Available at Vijay Sales outlets nationwide'),
    ('WH-CH720N - Coral Red', 'Sony', 12999, 12999, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Coral Red', 30, 3.8, 'https://your-store.example/headphone/wh-ch720n---coral-red', 'Not available in offline stores'),
    ('WH-1000XM5 - Space Gray (Bass-boosted signature)', 'Sony', 7999, 8690, 'In-Ear Wireless Neckband', 'Bass-boosted signature', 'Space Gray', 30, 4.5, 'https://your-store.example/headphone/wh-1000xm5---space-gray-bass-boosted-signature', 'Not available in offline stores'),
    ('Tune 760NC - Space Gray', 'JBL', 12999, 15850, 'Over-Ear Wired', 'Bass-boosted signature', 'Space Gray', 8, 3.4, 'https://your-store.example/headphone/tune-760nc---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Buds Pro 2 - Midnight Black (Crisp vocal clarity)', 'OnePlus', 5999, 7060, 'Over-Ear Wired', 'Crisp vocal clarity', 'Midnight Black', 45, 4.0, 'https://your-store.example/headphone/buds-pro-2---midnight-black-crisp-vocal-clarity', 'Available at Vijay Sales outlets nationwide'),
    ('HD 660S2 - Midnight Black (Crisp vocal clarity)', 'Sennheiser', 7999, 9090, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Midnight Black', 20, 3.8, 'https://your-store.example/headphone/hd-660s2---midnight-black-crisp-vocal-clarity', 'In stock at authorized brand stores in major cities'),
    ('QuietComfort Ultra - Sky Blue (Balanced sound with deep bass)', 'Bose', 1999, 2500, 'Active Noise Cancelling Over-Ear Wireless', 'Balanced sound with deep bass', 'Sky Blue', 0, 4.3, 'https://your-store.example/headphone/quietcomfort-ultra---sky-blue-balanced-sound-with-deep-bass', 'Available at Vijay Sales outlets nationwide'),
    ('QuietComfort 45 - Coral Red', 'Bose', 1999, 2440, 'Over-Ear Wired', 'Bass-boosted signature', 'Coral Red', 12, 4.5, 'https://your-store.example/headphone/quietcomfort-45---coral-red', 'Available at select Croma and Reliance Digital stores'),
    ('Rockerz 450 Pro - Space Gray', 'Boat', 7999, 8420, 'In-Ear Wireless Neckband', 'Immersive spatial audio', 'Space Gray', 15, 3.9, 'https://your-store.example/headphone/rockerz-450-pro---space-gray', 'Available at Vijay Sales outlets nationwide'),
    ('Rockerz 550 - Midnight Black (Crisp vocal clarity)', 'Boat', 5999, 6670, 'Over-Ear Wired', 'Crisp vocal clarity', 'Midnight Black', 30, 3.5, 'https://your-store.example/headphone/rockerz-550---midnight-black-crisp-vocal-clarity', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('SoundLink Around-Ear - Olive Green', 'Bose', 34999, 36840, 'In-Ear True Wireless', 'Immersive spatial audio', 'Olive Green', 15, 4.7, 'https://your-store.example/headphone/soundlink-around-ear---olive-green', 'Available at select Croma and Reliance Digital stores'),
    ('AirPods Pro 2 - Coral Red (Studio-grade audio)', 'Apple', 49999, 60970, 'Over-Ear Wired', 'Studio-grade audio', 'Coral Red', 15, 4.8, 'https://your-store.example/headphone/airpods-pro-2---coral-red-studio-grade-audio', 'Available at flagship brand stores only'),
    ('Indy ANC - Midnight Black', 'Skullcandy', 24999, 33330, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Midnight Black', 0, 4.0, 'https://your-store.example/headphone/indy-anc---midnight-black', 'Not available in offline stores'),
    ('Crusher ANC 2 - Ivory', 'Skullcandy', 29999, 34090, 'In-Ear True Wireless', 'Immersive spatial audio', 'Ivory', 8, 3.9, 'https://your-store.example/headphone/crusher-anc-2---ivory', 'Available at flagship brand stores only'),
    ('Buds 3 - Space Gray (Audiophile-tuned clarity)', 'OnePlus', 19999, 19999, 'In-Ear Wireless Neckband', 'Audiophile-tuned clarity', 'Space Gray', 20, 4.0, 'https://your-store.example/headphone/buds-3---space-gray-audiophile-tuned-clarity', 'Available at Vijay Sales outlets nationwide'),
    ('FreeBuds Pro 3 - Midnight Black', 'Huawei', 49999, 58820, 'In-Ear True Wireless', 'Balanced sound with deep bass', 'Midnight Black', 45, 4.0, 'https://your-store.example/headphone/freebuds-pro-3---midnight-black', 'In stock at authorized brand stores in major cities'),
    ('Galaxy Buds FE - Smoke White', 'Samsung', 14999, 16300, 'In-Ear True Wireless', 'Crisp vocal clarity', 'Smoke White', 12, 3.7, 'https://your-store.example/headphone/galaxy-buds-fe---smoke-white', 'Not available in offline stores'),
    ('HD 450BT - Smoke White', 'Sennheiser', 1499, 2000, 'Active Noise Cancelling Over-Ear Wireless', 'Audiophile-tuned clarity', 'Smoke White', 20, 3.8, 'https://your-store.example/headphone/hd-450bt---smoke-white', 'Available at flagship brand stores only'),
    ('WF-1000XM5 - Olive Green', 'Sony', 12999, 15290, 'Over-Ear Wired', 'Crisp vocal clarity', 'Olive Green', 30, 4.6, 'https://your-store.example/headphone/wf-1000xm5---olive-green', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('AirPods 3 - Ivory (Bass-boosted signature)', 'Apple', 24999, 28410, 'On-Ear Wired', 'Bass-boosted signature', 'Ivory', 0, 4.3, 'https://your-store.example/headphone/airpods-3---ivory-bass-boosted-signature', 'Available at Vijay Sales outlets nationwide'),
    ('Galaxy Buds3 - Coral Red', 'Samsung', 1499, 1870, 'In-Ear Wireless Neckband', 'Studio-grade audio', 'Coral Red', 5, 3.5, 'https://your-store.example/headphone/galaxy-buds3---coral-red', 'Available at Vijay Sales outlets nationwide'),
    ('LinkBuds S - Space Gray', 'Sony', 19999, 26670, 'In-Ear Wireless Neckband', 'Crisp vocal clarity', 'Space Gray', 2, 4.7, 'https://your-store.example/headphone/linkbuds-s---space-gray', 'Not available in offline stores'),
    ('Club Pro+ TWS - Coral Red', 'JBL', 19999, 26670, 'On-Ear Wired', 'Crisp vocal clarity', 'Coral Red', 12, 4.4, 'https://your-store.example/headphone/club-pro+-tws---coral-red', 'In stock at select Amazon/Flipkart partner retail stores'),
    ('AirPods Max - Olive Green (Audiophile-tuned clarity)', 'Apple', 2499, 2840, 'Over-Ear Wireless', 'Audiophile-tuned clarity', 'Olive Green', 12, 4.9, 'https://your-store.example/headphone/airpods-max---olive-green-audiophile-tuned-clarity', 'Available at Vijay Sales outlets nationwide');
